# Generated by Django 4.2.2 on 2025-01-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_surname', models.CharField(max_length=100, verbose_name='Yazar Soyadı')),
                ('author_name', models.CharField(max_length=100, verbose_name='Yazar Adı')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('rest', models.TextField(max_length=2000, verbose_name='Künyenin Kalanı')),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kısaltma (Opsiyonel)')),
            ],
        ),
    ]
