# Generated by Django 5.1.5 on 2025-01-28 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='randomsentence',
            name='ignored_by',
            field=models.ManyToManyField(blank=True, related_name='ignored_random_sentences', to=settings.AUTH_USER_MODEL),
        ),
    ]
