# Generated by Django 4.2.2 on 2025-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_cemil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cemil',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
