# Generated by Django 4.2.2 on 2025-01-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_secondary_button_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pagination_active_background_color',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pagination_active_text_color',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_family',
            field=models.CharField(default='EB Garamond', max_length=100),
        ),
    ]
