# Generated by Django 4.2.2 on 2025-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userprofile_nav_link_hover_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.IntegerField(default='16'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nav_link_hover_bg',
            field=models.CharField(default='#f5f5f5', max_length=7),
        ),
    ]
