# Generated by Django 4.2.2 on 2025-02-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_userprofile_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
