# Generated by Django 5.1.5 on 2025-02-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reference_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.answer'),
        ),
    ]
