# Generated by Django 5.1.5 on 2025-03-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_definition_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='metin_ismi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metin İsmi (Opsiyonel)'),
        ),
    ]
