# Generated by Django 5.1.5 on 2025-03-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reference_metin_ismi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cemil',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='message_bubble_color',
            field=models.CharField(default='#d1e7ff', max_length=7),
        ),
    ]
