# Generated by Django 5.1.5 on 2025-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_userprofile_cemil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tbas_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
