# Generated by Django 4.2.2 on 2025-06-05 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_userprofile_tbas_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='button_background_color',
            field=models.CharField(default='#6E8CA7', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='button_hover_background_color',
            field=models.CharField(default='#4E647E', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='font_size',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='link_color',
            field=models.CharField(default='#6E8CA7', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='link_hover_color',
            field=models.CharField(default='#4E647E', max_length=7),
        ),
        migrations.CreateModel(
            name='IATResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('gender', 'Cinsiyet'), ('ethnicity', 'Etnisite')], max_length=20)),
                ('dscore', models.FloatField()),
                ('bias_side', models.CharField(max_length=20)),
                ('errors', models.IntegerField()),
                ('avg_rt', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
