# Generated by Django 4.2.2 on 2025-06-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_kenarda'),
    ]

    operations = [
        migrations.AddField(
            model_name='kenarda',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kenarda_taslaklar', to='core.question'),
        ),
    ]
