# Generated by Django 4.2.2 on 2025-06-13 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_cikistesti_cikistestisoru_cikistestisik'),
    ]

    operations = [
        migrations.AddField(
            model_name='cikistestisoru',
            name='correct_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.cikistestisik'),
        ),
    ]
