# Generated by Django 4.2.2 on 2025-06-13 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_cikistestisoru_correct_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='CikisTestiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('dogru_sayisi', models.PositiveIntegerField()),
                ('toplam_soru', models.PositiveIntegerField()),
                ('cikis_dogrusu_uydu', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='core.cikistesti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
