# Generated by Django 4.2.2 on 2025-06-18 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_delphoirequest_delphoiprophecy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delphoiprophecy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='delphoiprophecy',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='delphoirequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='delphoirequest',
            unique_together={('user', 'requested_at', 'question')},
        ),
    ]
