# Generated by Django 4.2.2 on 2025-11-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_questionfollow_notification_answerfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('new_answer', 'New Answer'), ('answer_update', 'Answer Update'), ('question_update', 'Question Update'), ('new_subquestion', 'New Subquestion'), ('followed_user_entry', 'Followed User Entry'), ('system', 'System')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', '-created_at'], name='core_answer_questio_6a8d74_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user', '-created_at'], name='core_answer_user_id_5a136d_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-created_at'], name='core_answer_created_8b24ba_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['user', '-created_at'], name='core_questi_user_id_1dac96_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='core_questi_created_e034c2_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_text'], name='core_questi_questio_5e1786_idx'),
        ),
    ]
