# Generated by Django 4.2.2 on 2025-11-04 04:19

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Tüm mevcut soruların slug'larını oluştur"""
    Question = apps.get_model('core', 'Question')

    for question in Question.objects.all():
        if not question.slug:
            # Slug oluştur
            base_slug = slugify(question.question_text, allow_unicode=True)[:250]
            slug = base_slug

            # Eğer slug zaten varsa sonuna sayı ekle
            counter = 1
            while Question.objects.filter(slug=slug).exclude(pk=question.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            question.slug = slug
            question.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Geri alma fonksiyonu (slug'ları temizle)"""
    Question = apps.get_model('core', 'Question')
    Question.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_question_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
