# Generated by Django 4.2.2 on 2025-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_populate_question_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, blank=True),
        ),
    ]
