# Generated by Django 4.2.2 on 2025-11-12 16:36

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_alter_question_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dj',
            field=models.BooleanField(default=False, verbose_name='DJ Yetkisi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[core.validators.validate_image_file]),
        ),
        migrations.CreateModel(
            name='RadioProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Program Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(verbose_name='Bitiş Zamanı')),
                ('is_live', models.BooleanField(default=False, verbose_name='Canlı Yayında')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('agora_channel_name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Agora Kanal Adı')),
                ('listener_count', models.PositiveIntegerField(default=0, verbose_name='Dinleyici Sayısı')),
                ('max_listeners', models.PositiveIntegerField(default=0, verbose_name='Max Dinleyici')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_programs', to=settings.AUTH_USER_MODEL, verbose_name='DJ')),
            ],
            options={
                'verbose_name': 'Radyo Programı',
                'verbose_name_plural': 'Radyo Programları',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time'], name='core_radiop_start_t_0efff6_idx'), models.Index(fields=['is_live'], name='core_radiop_is_live_62beff_idx')],
            },
        ),
    ]
