# Generated by Django 4.2.2 on 2025-11-22 08:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_question_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[core.validators.validate_image_file]),
        ),
    ]
