# Generated by Django 4.2.2 on 2025-11-22 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_alter_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='core.question')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='core.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['parent', 'user'], name='core_questi_parent__7730a2_idx'), models.Index(fields=['child', 'user'], name='core_questi_child_i_138c4e_idx'), models.Index(fields=['user', '-created_at'], name='core_questi_user_id_2dafbe_idx')],
                'unique_together': {('parent', 'child', 'user')},
            },
        ),
    ]
