# Generated by Django 4.2.2 on 2025-11-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_questionrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomsentence',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='randomsentence',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
