# Generated by Django 4.2.2 on 2025-11-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_userprofile_is_dj_alter_userprofile_photo_and_more'),
        ('core', '0035_randomsentence_downvotes_randomsentence_upvotes'),
    ]

    operations = [
    ]
