# Generated by Django 4.2.2 on 2025-11-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_merge_20251126_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='excluded_words',
            field=models.TextField(blank=True, default='', help_text='Virgülle ayrılmış çıkarılacak kelimeler'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='metin_ismi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metin İsmi'),
        ),
    ]
