# Generated by Django 4.2.2 on 2025-12-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_userprofile_excluded_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('new_answer', 'New Answer'), ('answer_update', 'Answer Update'), ('question_update', 'Question Update'), ('new_subquestion', 'New Subquestion'), ('followed_user_entry', 'Followed User Entry'), ('new_follower', 'New Follower'), ('system', 'System')], max_length=20),
        ),
    ]
