# Generated by Django 4.2.2 on 2025-12-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kenarda',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kenarda_edits', to='core.answer'),
        ),
    ]
