# Generated by Django 4.2.2 on 2025-12-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_kenarda_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kenarda',
            name='draft_source',
            field=models.CharField(blank=True, choices=[('starting_question', 'Başlangıç Sorusu'), ('question_from_search', 'Aramadan Soru'), ('answer_edit', 'Yanıt Düzenleme')], max_length=30, null=True),
        ),
    ]
