# Generated by Django 4.2.2 on 2026-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_libraryfile_userprofile_can_upload_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('new_answer', 'New Answer'), ('answer_update', 'Answer Update'), ('question_update', 'Question Update'), ('new_subquestion', 'New Subquestion'), ('followed_user_entry', 'Followed User Entry'), ('new_follower', 'New Follower'), ('question_follow', 'Question Follow'), ('answer_vote', 'Answer Vote'), ('answer_save', 'Answer Save'), ('system', 'System')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('visitor_hash', models.CharField(max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-last_seen_at'],
                'indexes': [models.Index(fields=['date', 'visitor_hash'], name='core_dailyv_date_037458_idx')],
                'unique_together': {('date', 'visitor_hash')},
            },
        ),
    ]
