# Generated by Django 4.2.2 on 2026-03-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_initial_answer_revisions(apps, schema_editor):
    Answer = apps.get_model('core', 'Answer')
    AnswerRevision = apps.get_model('core', 'AnswerRevision')

    existing_answer_ids = set(
        AnswerRevision.objects.values_list('answer_id', flat=True)
    )
    revisions_to_create = []

    for answer in Answer.objects.select_related('user').iterator():
        if answer.id in existing_answer_ids:
            continue
        revisions_to_create.append(
            AnswerRevision(
                answer_id=answer.id,
                parent_revision_id=None,
                base_revision_id=None,
                accepted_suggestion_id=None,
                created_by_id=answer.user_id,
                content=answer.answer_text or '',
                revision_no=1,
                source='initial',
                change_summary='İlk yayın',
                is_current=True,
                created_at=answer.created_at,
            )
        )

    if revisions_to_create:
        AnswerRevision.objects.bulk_create(revisions_to_create, batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_alter_notification_notification_type_dailyvisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('revision_no', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('initial', 'Initial'), ('author_edit', 'Author Edit'), ('suggestion_merge', 'Suggestion Merge')], default='author_edit', max_length=24)),
                ('change_summary', models.CharField(blank=True, default='', max_length=255)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-revision_no', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_text', models.TextField()),
                ('change_summary', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('outdated', 'Outdated')], db_index=True, default='open', max_length=12)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_suggestions', to='core.answer')),
                ('base_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_suggestions', to='core.answerrevision')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_suggestions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_answer_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='accepted_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_into_revisions', to='core.answersuggestion'),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.answer'),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='base_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='based_revisions', to='core.answerrevision'),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='parent_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_revisions', to='core.answerrevision'),
        ),
        migrations.AddIndex(
            model_name='answersuggestion',
            index=models.Index(fields=['answer', 'status'], name='core_answer_answer__392cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='answersuggestion',
            index=models.Index(fields=['proposed_by', '-created_at'], name='core_answer_propose_bc5eff_idx'),
        ),
        migrations.AddIndex(
            model_name='answerrevision',
            index=models.Index(fields=['answer', 'is_current'], name='core_answer_answer__e3d37c_idx'),
        ),
        migrations.AddIndex(
            model_name='answerrevision',
            index=models.Index(fields=['answer', '-created_at'], name='core_answer_answer__a1781e_idx'),
        ),
        migrations.AddIndex(
            model_name='answerrevision',
            index=models.Index(fields=['created_by', '-created_at'], name='core_answer_created_b4f45b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answerrevision',
            unique_together={('answer', 'revision_no')},
        ),
        migrations.RunPython(seed_initial_answer_revisions, noop_reverse),
    ]
