# Generated by Django 4.2.2 on 2026-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_answerrevision_answersuggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('new_answer', 'New Answer'), ('answer_update', 'Answer Update'), ('question_update', 'Question Update'), ('new_subquestion', 'New Subquestion'), ('followed_user_entry', 'Followed User Entry'), ('new_follower', 'New Follower'), ('question_follow', 'Question Follow'), ('answer_vote', 'Answer Vote'), ('answer_save', 'Answer Save'), ('answer_suggestion', 'Answer Suggestion'), ('suggestion_result', 'Suggestion Result'), ('system', 'System')], max_length=20),
        ),
    ]
