# Generated by Django 4.2.2 on 2026-03-20 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('new_answer', 'New Answer'), ('answer_update', 'Answer Update'), ('question_update', 'Question Update'), ('new_subquestion', 'New Subquestion'), ('followed_user_entry', 'Followed User Entry'), ('new_follower', 'New Follower'), ('question_follow', 'Question Follow'), ('answer_vote', 'Answer Vote'), ('answer_save', 'Answer Save'), ('answer_suggestion', 'Answer Suggestion'), ('suggestion_result', 'Suggestion Result'), ('revision_review', 'Revision Review'), ('system', 'System')], max_length=20),
        ),
        migrations.CreateModel(
            name='AnswerRevisionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.answerrevision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_revision_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'user__username'],
                'indexes': [models.Index(fields=['revision', 'status'], name='core_answer_revisio_ee073f_idx'), models.Index(fields=['user', 'status'], name='core_answer_user_id_199e80_idx')],
                'unique_together': {('revision', 'user')},
            },
        ),
    ]
