# Generated by Django 4.2.2 on 2026-03-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='left_frame_pin_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sol frame sira'),
        ),
        migrations.AddField(
            model_name='question',
            name='left_frame_pin_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Bos birakilirsa sabitleme manuel kaldirilana kadar devam eder.', null=True, verbose_name='Sol frame sabit bitis'),
        ),
        migrations.AddField(
            model_name='question',
            name='left_frame_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Sol frame sabit'),
        ),
    ]
