# Generated by Django 4.2.2 on 2026-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_question_left_frame_pin_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='answer_background_color',
            field=models.CharField(default='#F5F0E6', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='#F5F0E6', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='button_background_color',
            field=models.CharField(default='#B08D57', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='button_hover_background_color',
            field=models.CharField(default='#9A7747', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='button_text_color',
            field=models.CharField(default='#FAF7F0', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='content_background_color',
            field=models.CharField(default='#FFF9F0', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dropdown_hover_background_color',
            field=models.CharField(default='#E7DFD2', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dropdown_hover_text_color',
            field=models.CharField(default='#22312B', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dropdown_text_color',
            field=models.CharField(default='#1F1A14', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='font_family',
            field=models.CharField(default='Crimson+Text', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='font_size',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='header_background_color',
            field=models.CharField(default='#22312B', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='header_text_color',
            field=models.CharField(default='#F7F2E8', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hover_background_color',
            field=models.CharField(default='#E7DFD2', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icon_color',
            field=models.CharField(default='#22312B', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icon_hover_color',
            field=models.CharField(default='#B08D57', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='link_color',
            field=models.CharField(default='#2F6B4F', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='link_hover_color',
            field=models.CharField(default='#1E4D38', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='message_bubble_color',
            field=models.CharField(default='#DCE8DE', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nav_link_hover_bg',
            field=models.CharField(default='#2B3D35', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nav_link_hover_color',
            field=models.CharField(default='#FAF7F0', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pagination_background_color',
            field=models.CharField(default='#FFF9F0', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pagination_text_color',
            field=models.CharField(default='#22312B', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_button_background_color',
            field=models.CharField(default='#2E3A2F', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_button_hover_background_color',
            field=models.CharField(default='#243028', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_button_text_color',
            field=models.CharField(default='#F7F2E8', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tab_active_background_color',
            field=models.CharField(default='#FFF9F0', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tab_active_text_color',
            field=models.CharField(default='#22312B', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tab_background_color',
            field=models.CharField(default='#EFE6D8', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tab_text_color',
            field=models.CharField(default='#1F1A14', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tbas_color',
            field=models.CharField(default='#1F1A14', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='text_color',
            field=models.CharField(default='#1F1A14', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='yanit_card',
            field=models.CharField(default='#FFF9F0', max_length=7),
        ),
    ]
