# Generated by Django 4.2.2 on 2026-04-09 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0050_alter_userprofile_answer_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_online_created_687dea_idx'), models.Index(fields=['user', 'created_at'], name='core_online_user_id_e9a89f_idx')],
            },
        ),
    ]
