# Generated by Django 4.2.2 on 2026-04-11 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0051_onlinechatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Hakaret / Saldırgan içerik'), ('offtopic', 'Konu dışı'), ('misinfo', 'Yanıltıcı / sorunlu içerik'), ('copyright', 'Telif ihlali'), ('other', 'Diğer')], max_length=24)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('reviewed', 'İncelendi'), ('dismissed', 'Reddedildi'), ('actioned', 'İşlem uygulandı')], db_index=True, default='open', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.savedcollection')),
                ('saved_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_links', to='core.saveditem')),
            ],
            options={
                'indexes': [models.Index(fields=['collection', 'created_at'], name='core_savedc_collect_d777ee_idx'), models.Index(fields=['saved_item'], name='core_savedc_saved_i_cf3e22_idx')],
                'unique_together': {('collection', 'saved_item')},
            },
        ),
        migrations.AddIndex(
            model_name='savedcollection',
            index=models.Index(fields=['user', 'name'], name='core_savedc_user_id_df2af0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedcollection',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['status', '-created_at'], name='core_conten_status_90e95e_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['content_type', 'object_id'], name='core_conten_content_72da96_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['reporter', '-created_at'], name='core_conten_reporte_a88503_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentreport',
            unique_together={('reporter', 'content_type', 'object_id')},
        ),
    ]
