# Generated by Django 4.2.2 on 2026-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_0054_attendance_online_chat'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='core_messag_recipie_ffa7b4_idx'),
        ),
    ]
