# Generated by Django 4.2.2 on 2026-07-24 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_message_core_messag_recipie_ffa7b4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EntryBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to='core.answer')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.entrybook')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='entrybook',
            name='answers',
            field=models.ManyToManyField(related_name='entry_books', through='core.EntryBookItem', to='core.answer'),
        ),
        migrations.AddField(
            model_name='entrybook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='entrybookitem',
            index=models.Index(fields=['book', 'position'], name='core_entryb_book_id_95d68a_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrybookitem',
            constraint=models.UniqueConstraint(fields=('book', 'answer'), name='unique_answer_per_entry_book'),
        ),
        migrations.AddConstraint(
            model_name='entrybookitem',
            constraint=models.UniqueConstraint(fields=('book', 'position'), name='unique_position_per_entry_book'),
        ),
        migrations.AddIndex(
            model_name='entrybook',
            index=models.Index(fields=['user', '-updated_at'], name='core_entryb_user_id_27bcc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrybook',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_entry_book_title_per_user'),
        ),
    ]
