# Generated by Django 4.2.2 on 2026-07-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_entrybook_entrybookitem_entrybook_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.answersuggestion'),
        ),
        migrations.AlterField(
            model_name='answersuggestion',
            name='status',
            field=models.CharField(choices=[('open', 'Bekliyor'), ('accepted', 'Kabul edildi'), ('rejected', 'Reddedildi'), ('outdated', 'Güncelliğini yitirdi')], db_index=True, default='open', max_length=12),
        ),
    ]
