# Generated by Django 4.2.2 on 2026-08-10 20:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0058_notification_related_suggestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_slug', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('not_started', 'Başlanmadı'), ('started', 'Devam ediyor'), ('completed', 'Tamamlandı')], default='not_started', max_length=16)),
                ('last_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('best_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_opened_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantık dersi ilerlemesi',
                'verbose_name_plural': 'Mantık dersi ilerlemeleri',
                'ordering': ['-last_opened_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_logicl_user_id_e375bc_idx'), models.Index(fields=['user', '-last_opened_at'], name='core_logicl_user_id_2c03f0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='logiclessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson_slug'), name='unique_logic_progress_per_user_lesson'),
        ),
    ]
