# Generated by Django 4.2.2 on 2026-08-24 05:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0059_logic_lesson_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('color', models.CharField(default='#2F6B4F', max_length=7)),
                ('icon', models.CharField(choices=[('check2-circle', 'Genel'), ('book', 'Okuma'), ('droplet', 'Su'), ('activity', 'Hareket'), ('sun', 'Sabah'), ('moon-stars', 'Uyku'), ('heart-pulse', 'Sağlık'), ('pencil', 'Yazma'), ('briefcase', 'İş'), ('leaf', 'Denge')], default='check2-circle', max_length=24)),
                ('frequency', models.CharField(choices=[('daily', 'Her gün'), ('custom', 'Belirli günler')], default='daily', max_length=12)),
                ('schedule_days', models.JSONField(blank=True, default=list)),
                ('target', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('unit', models.CharField(default='kez', max_length=18)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alışkanlık',
                'verbose_name_plural': 'Alışkanlıklar',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.habit')),
            ],
            options={
                'verbose_name': 'Alışkanlık kaydı',
                'verbose_name_plural': 'Alışkanlık kayıtları',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['habit', '-date'], name='core_habite_habit_i_3eac8c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_entry_per_day'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_archived', 'position'], name='core_habit_user_id_14efea_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'start_date'], name='core_habit_user_id_36ad9f_idx'),
        ),
    ]
