# Generated by Django 4.2.2 on 2026-08-24 19:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0060_habit_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('expense', 'Gider'), ('income', 'Gelir')], max_length=10)),
                ('color', models.CharField(default='#B85C4A', max_length=7)),
                ('icon', models.CharField(default='tag', max_length=24)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Para kategorisi',
                'verbose_name_plural': 'Para kategorileri',
                'ordering': ['kind', 'position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='habitentry',
            name='target',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expense', 'Gider'), ('income', 'Gelir')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.moneycategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Para hareketi',
                'verbose_name_plural': 'Para hareketleri',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='core_moneyt_user_id_a820d5_idx'), models.Index(fields=['user', 'kind', '-date'], name='core_moneyt_user_id_389504_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='moneycategory',
            index=models.Index(fields=['user', 'kind', 'position'], name='core_moneyc_user_id_977535_idx'),
        ),
        migrations.AddConstraint(
            model_name='moneycategory',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'name'), name='unique_money_category_per_user_kind'),
        ),
    ]
