# Generated by Django 4.2.2 on 2026-08-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_habit_daily_targets_and_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.CharField(choices=[('check2-circle', 'Genel'), ('bullseye', 'Hedef'), ('star', 'Yıldız'), ('trophy', 'Başarı'), ('lightning-charge', 'Enerji'), ('book', 'Okuma'), ('journal-check', 'Çalışma'), ('mortarboard', 'Eğitim'), ('lightbulb', 'Öğrenme'), ('code-slash', 'Kodlama'), ('translate', 'Dil'), ('droplet', 'Su'), ('activity', 'Hareket'), ('bicycle', 'Bisiklet'), ('sun', 'Sabah'), ('moon-stars', 'Uyku'), ('alarm', 'Saat'), ('calendar-check', 'Plan'), ('heart-pulse', 'Sağlık'), ('pencil', 'Yazma'), ('briefcase', 'İş'), ('palette', 'Sanat'), ('music-note-beamed', 'Müzik'), ('camera', 'Fotoğraf'), ('brush', 'Üretim'), ('controller', 'Oyun'), ('cup-hot', 'Mola'), ('people', 'Sosyal'), ('house-heart', 'Ev'), ('wallet2', 'Bütçe'), ('piggy-bank', 'Birikim'), ('basket', 'Alışveriş'), ('egg-fried', 'Beslenme'), ('emoji-smile', 'İyi oluş'), ('flower1', 'Bakım'), ('tree', 'Denge')], default='check2-circle', max_length=24),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('new_answer', 'New Answer'), ('answer_update', 'Answer Update'), ('question_update', 'Question Update'), ('new_subquestion', 'New Subquestion'), ('followed_user_entry', 'Followed User Entry'), ('new_follower', 'New Follower'), ('question_follow', 'Question Follow'), ('answer_vote', 'Answer Vote'), ('answer_save', 'Answer Save'), ('answer_suggestion', 'Answer Suggestion'), ('suggestion_result', 'Suggestion Result'), ('revision_review', 'Revision Review'), ('habit_reminder', 'Habit Reminder'), ('system', 'System')], max_length=20),
        ),
        migrations.CreateModel(
            name='HabitReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to='core.habit')),
            ],
            options={
                'verbose_name': 'Alışkanlık hatırlatma teslimi',
                'verbose_name_plural': 'Alışkanlık hatırlatma teslimleri',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['habit', '-date'], name='core_habitr_habit_i_774e2b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='habitreminderdelivery',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_reminder_delivery_per_day'),
        ),
    ]
