# Generated by Django 4.2.2 on 2026-09-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_attendance_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('entry_reference', 'Entry Reference'), ('new_answer', 'New Answer'), ('answer_update', 'Answer Update'), ('question_update', 'Question Update'), ('new_subquestion', 'New Subquestion'), ('followed_user_entry', 'Followed User Entry'), ('new_follower', 'New Follower'), ('question_follow', 'Question Follow'), ('answer_vote', 'Answer Vote'), ('answer_save', 'Answer Save'), ('answer_suggestion', 'Answer Suggestion'), ('suggestion_result', 'Suggestion Result'), ('revision_review', 'Revision Review'), ('habit_reminder', 'Habit Reminder'), ('system', 'System')], max_length=20),
        ),
        migrations.CreateModel(
            name='EntryReferenceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_notices_sent', to='core.answer')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_notices_received', to='core.answer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entryreferencenotice',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_entry_reference_notice'),
        ),
    ]
