from copy import deepcopy
from random import SystemRandom


A1_LEVEL_TEST_MODULES = [
    {
        "id": "foundations",
        "title": "Temel iletişim ve çekim",
        "description": "Selamlaşma, artikeller, zamirler ve sein temeli.",
        "sample_size": 10,
    },
    {
        "id": "identity",
        "title": "Kimlik, köken ve soru düzeni",
        "description": "Sayılar, yaş, ülke-şehir, milliyet ve soru cümlesi düzeni.",
        "sample_size": 10,
    },
    {
        "id": "daily_life",
        "title": "Sahiplik ve günlük hayat",
        "description": "haben, iyelik kalıpları, rutinler ve temel zaman kullanımı.",
        "sample_size": 10,
    },
    {
        "id": "space_time",
        "title": "Mekân, zaman ve program",
        "description": "ein/eine/kein, yer sorma, saatler, günler ve ayrılabilen fiiller.",
        "sample_size": 10,
    },
    {
        "id": "objects_orders",
        "title": "Nesneler, sipariş ve Akkusativ",
        "description": "Maskulin nesne değişimi, yiyecek-içecek ve sipariş kalıpları.",
        "sample_size": 10,
    },
]


A1_LEVEL_TEST_BANK = [
    {
        "id": "a1-001",
        "module_id": "foundations",
        "prompt": '"___ Name ist wichtig." cümlesinde doğru artikel hangisi?',
        "options": ["der", "die", "das"],
        "correct": "der",
        "explanation": "Name maskulin isimdir; der Name olarak öğrenilir.",
    },
    {
        "id": "a1-002",
        "module_id": "foundations",
        "prompt": 'Sabah birine günaydın demek için hangi kalıp uygundur?',
        "options": ["Guten Morgen!", "Guten Abend!", "Tschüss!"],
        "correct": "Guten Morgen!",
        "explanation": "Sabah saatlerinde en temel selamlaşma Guten Morgen olur.",
    },
    {
        "id": "a1-003",
        "module_id": "foundations",
        "prompt": '"Benim adım Elif." cümlesinin en doğal karşılığı hangisi?',
        "options": ["Ich heiße Elif.", "Ich bin Elif.", "Mein Elif ist."],
        "correct": "Ich heiße Elif.",
        "explanation": "Ad söylemenin en temel kalıbı Ich heiße ... yapısıdır.",
    },
    {
        "id": "a1-004",
        "module_id": "foundations",
        "prompt": '"biz" anlamına gelen zamir hangisidir?',
        "options": ["wir", "ihr", "sie"],
        "correct": "wir",
        "explanation": "wir = biz; ihr = siz, sie = onlar/o kadın bağlama göre değişir.",
    },
    {
        "id": "a1-005",
        "module_id": "foundations",
        "prompt": 'du zamiri ile sein fiilinin doğru çekimi hangisidir?',
        "options": ["bin", "bist", "seid"],
        "correct": "bist",
        "explanation": "du ile sein fiili bist olarak çekilir.",
    },
    {
        "id": "a1-006",
        "module_id": "foundations",
        "prompt": '"Sie ist müde." cümlesinin doğru Türkçesi hangisidir?',
        "options": ["O yorgun.", "Siz yorgunsunuz.", "Onlar yorgun."],
        "correct": "O yorgun.",
        "explanation": "Buradaki Sie değil, sie/eril olmayan tekil özne kullanımıdır: o kadın yorgun.",
    },
    {
        "id": "a1-007",
        "module_id": "foundations",
        "prompt": '"Wie geht es dir?" sorusuna uygun kısa cevap hangisidir?',
        "options": ["Mir geht es gut.", "Ich heiße gut.", "Ich bin dir gut."],
        "correct": "Mir geht es gut.",
        "explanation": "Hâl-hatır kalıbı sabit ifade olarak Mir geht es ... şeklinde cevaplanır.",
    },
    {
        "id": "a1-008",
        "module_id": "foundations",
        "prompt": '"Das ist Frau Kaya." cümlesi ne anlatır?',
        "options": ["Bu Bayan Kaya.", "Bayan Kaya benimdir.", "Bayan Kaya nerede?"],
        "correct": "Bu Bayan Kaya.",
        "explanation": "Das ist ... kalıbı birini veya bir şeyi tanıtmak için kullanılır.",
    },
    {
        "id": "a1-009",
        "module_id": "foundations",
        "prompt": 'Buch kelimesinin doğru artikeli hangisidir?',
        "options": ["der", "die", "das"],
        "correct": "das",
        "explanation": "Kitap Almancada das Buch olarak kullanılır.",
    },
    {
        "id": "a1-010",
        "module_id": "foundations",
        "prompt": 'Resmî hitapta "Siz" için doğru yapı hangisidir?',
        "options": ["Sie sind", "Sie ist", "Sie seid"],
        "correct": "Sie sind",
        "explanation": "Büyük harfli Sie resmî siz demektir ve sind ile kullanılır.",
    },
    {
        "id": "a1-011",
        "module_id": "identity",
        "prompt": '"Kaç yaşındasın?" sorusunun doğru Almancası hangisidir?',
        "options": ["Wie alt bist du?", "Wie heißt du?", "Wo wohnst du?"],
        "correct": "Wie alt bist du?",
        "explanation": "Yaş sormak için Wie alt bist du? kalıbı kullanılır.",
    },
    {
        "id": "a1-012",
        "module_id": "identity",
        "prompt": '"Ben 23 yaşındayım." cümlesi hangisidir?',
        "options": ["Ich bin 23 Jahre alt.", "Ich habe 23 Jahre.", "Ich heiße 23 Jahre alt."],
        "correct": "Ich bin 23 Jahre alt.",
        "explanation": "Yaş, Almancada sein fiiliyle kurulur; haben kullanılmaz.",
    },
    {
        "id": "a1-013",
        "module_id": "identity",
        "prompt": '"Ben Ankara\'danım." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bin aus Ankara.", "Ich bin in Ankara.", "Ich komme in Ankara."],
        "correct": "Ich bin aus Ankara.",
        "explanation": "aus köken ya da geldiğin yer bilgisini verir.",
    },
    {
        "id": "a1-014",
        "module_id": "identity",
        "prompt": '"Ben Berlin\'deyim." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bin in Berlin.", "Ich bin aus Berlin.", "Ich heiße Berlin."],
        "correct": "Ich bin in Berlin.",
        "explanation": "in bulunduğun yeri anlatır.",
    },
    {
        "id": "a1-015",
        "module_id": "identity",
        "prompt": '"Ben Almanım." cümlesi hangisidir?',
        "options": ["Ich bin deutsch.", "Ich bin Deutschland.", "Ich heiße deutsch."],
        "correct": "Ich bin deutsch.",
        "explanation": "Milliyet ya da dil bilgisi çoğu zaman sıfat gibi kullanılır: deutsch.",
    },
    {
        "id": "a1-016",
        "module_id": "identity",
        "prompt": 'Türkiye için doğru köken cümlesi hangisidir?',
        "options": ["Ich komme aus der Türkei.", "Ich komme aus Türkei.", "Ich komme in der Türkei."],
        "correct": "Ich komme aus der Türkei.",
        "explanation": "die Türkei artikel aldığı için aus der Türkei kalıbı kurulur.",
    },
    {
        "id": "a1-017",
        "module_id": "identity",
        "prompt": 'du zamiri ile wohnen fiilinin doğru çekimi hangisidir?',
        "options": ["wohnst", "wohnen", "wohnt"],
        "correct": "wohnst",
        "explanation": "du ile düzenli fiiller çoğu zaman -st eki alır: du wohnst.",
    },
    {
        "id": "a1-018",
        "module_id": "identity",
        "prompt": '"Nerede çalışıyorsun?" sorusunun doğru Almancası hangisidir?',
        "options": ["Wo arbeitest du?", "Wer arbeitest du?", "Wann arbeitest du?"],
        "correct": "Wo arbeitest du?",
        "explanation": "Yer sorularında Wo kullanılır ve fiil ikinci pozisyondadır.",
    },
    {
        "id": "a1-019",
        "module_id": "identity",
        "prompt": 'Doğru evet-hayır sorusu hangisidir?',
        "options": ["Kommst du aus Izmir?", "Du kommst aus Izmir?", "Wo du kommst aus Izmir?"],
        "correct": "Kommst du aus Izmir?",
        "explanation": "Soru kelimesi yoksa fiil başa geçer.",
    },
    {
        "id": "a1-020",
        "module_id": "identity",
        "prompt": '"Was studierst du?" sorusu ne demektir?',
        "options": ["Ne okuyorsun / hangi bölümü okuyorsun?", "Nerede çalışıyorsun?", "Kaç yaşındasın?"],
        "correct": "Ne okuyorsun / hangi bölümü okuyorsun?",
        "explanation": "was, içerik veya nesne sorar; studieren ile bölüm/öğrenim içeriği sorulur.",
    },
    {
        "id": "a1-021",
        "module_id": "daily_life",
        "prompt": '"Benim bir kitabım var." cümlesi hangisidir?',
        "options": ["Ich habe ein Buch.", "Ich bin ein Buch.", "Ich habe der Buch."],
        "correct": "Ich habe ein Buch.",
        "explanation": "Sahiplik cümleleri haben ile kurulur.",
    },
    {
        "id": "a1-022",
        "module_id": "daily_life",
        "prompt": '"benim kardeşim" ifadesinin doğru biçimi hangisidir?',
        "options": ["mein Bruder", "ich Bruder", "sein Bruder"],
        "correct": "mein Bruder",
        "explanation": "İyelik, isimden önce gelen mein/dein/sein gibi sözlerle kurulur.",
    },
    {
        "id": "a1-023",
        "module_id": "daily_life",
        "prompt": '"Bu benim kız kardeşim." cümlesi hangisidir?',
        "options": ["Das ist meine Schwester.", "Ich habe meine Schwester.", "Meine Schwester ist das."],
        "correct": "Das ist meine Schwester.",
        "explanation": "Birini tanıtmak için Das ist ... kalıbı kullanılır.",
    },
    {
        "id": "a1-024",
        "module_id": "daily_life",
        "prompt": '"Bizim iki sandalyemiz var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir haben zwei Stühle.", "Wir sind zwei Stühle.", "Wir haben zwei Stuhl."],
        "correct": "Wir haben zwei Stühle.",
        "explanation": "Haben sahipliği kurar; çoğul biçim Stühle olur.",
    },
    {
        "id": "a1-025",
        "module_id": "daily_life",
        "prompt": '"Bugün Almanca öğreniyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Heute lerne ich Deutsch.", "Am heute lerne ich Deutsch.", "Heute ich lerne Deutsch."],
        "correct": "Heute lerne ich Deutsch.",
        "explanation": "Zaman ifadesi başta olsa bile fiil ikinci yerde kalır.",
    },
    {
        "id": "a1-026",
        "module_id": "daily_life",
        "prompt": '"Sabahları kahve içiyorum." cümlesi hangisidir?',
        "options": ["Morgens trinke ich Kaffee.", "Am morgens ich trinke Kaffee.", "Ich morgens Kaffee trinke."],
        "correct": "Morgens trinke ich Kaffee.",
        "explanation": "morgens yalın zaman zarfıdır; cümle başına gelince fiil ikinci pozisyonda kalır.",
    },
    {
        "id": "a1-027",
        "module_id": "daily_life",
        "prompt": '"Ben cuma günü çalışıyorum." cümlesi hangisidir?',
        "options": ["Ich arbeite am Freitag.", "Ich arbeite um Freitag.", "Ich arbeite Freitag am."],
        "correct": "Ich arbeite am Freitag.",
        "explanation": "Gün adları ile temel kullanım am + gün şeklindedir.",
    },
    {
        "id": "a1-028",
        "module_id": "daily_life",
        "prompt": '"Kurs saat sekizde başlıyor." cümlesi hangisidir?',
        "options": ["Der Kurs beginnt um acht Uhr.", "Der Kurs beginnt am acht Uhr.", "Der Kurs acht Uhr beginnt."],
        "correct": "Der Kurs beginnt um acht Uhr.",
        "explanation": "Saat anlatımında um + saat kullanılır.",
    },
    {
        "id": "a1-029",
        "module_id": "daily_life",
        "prompt": 'Doğru cümle hangisidir?',
        "options": ["Heute lerne ich Deutsch.", "Heute ich lerne Deutsch.", "Ich heute lerne Deutsch."],
        "correct": "Heute lerne ich Deutsch.",
        "explanation": "Başta zaman varsa fiil yine ikinci sıradadır.",
    },
    {
        "id": "a1-030",
        "module_id": "daily_life",
        "prompt": '"Akşamları kitap okuyorum." cümlesi hangisidir?',
        "options": ["Abends lese ich ein Buch.", "Ich lese ein Buch abends.", "Abends ich lese ein Buch."],
        "correct": "Abends lese ich ein Buch.",
        "explanation": "abends ile cümle başına zaman getirip fiili ikinci sırada tutuyoruz.",
    },
    {
        "id": "a1-031",
        "module_id": "space_time",
        "prompt": 'Yeni bir nesne tanıtılırken hangi yapı daha uygundur?',
        "options": ["ein Tisch", "der Tisch", "den Tisch"],
        "correct": "ein Tisch",
        "explanation": "İlk kez tanıtılan veya belirsiz nesne için çoğu zaman ein/eine kullanılır.",
    },
    {
        "id": "a1-032",
        "module_id": "space_time",
        "prompt": '"Benim bilgisayarım yok." cümlesi hangisidir?',
        "options": ["Ich habe keinen Computer.", "Ich habe nicht Computer.", "Ich bin kein Computer."],
        "correct": "Ich habe keinen Computer.",
        "explanation": "Bilgisayar maskulin nesnedir; olumsuzluk keinen ile kurulur.",
    },
    {
        "id": "a1-033",
        "module_id": "space_time",
        "prompt": '"Kitap nerede?" sorusuna en kısa uygun cevap hangisidir?',
        "options": ["Dort.", "Aus Ankara.", "Zwanzig."],
        "correct": "Dort.",
        "explanation": "Yer sorusuna burada/şurada gibi kısa cevaplar verilebilir.",
    },
    {
        "id": "a1-034",
        "module_id": "space_time",
        "prompt": '"Bir banyo var." cümlesi hangisidir?',
        "options": ["Es gibt ein Bad.", "Es hat ein Bad.", "Es ist ein Bad."],
        "correct": "Es gibt ein Bad.",
        "explanation": "Var-yok anlatımında Es gibt yapısı kullanılır.",
    },
    {
        "id": "a1-035",
        "module_id": "space_time",
        "prompt": '"Bir mutfak var mı?" sorusunun doğru biçimi hangisidir?',
        "options": ["Gibt es eine Küche?", "Es gibt eine Küche?", "Wo ist eine Küche?"],
        "correct": "Gibt es eine Küche?",
        "explanation": "Es gibt soruya çevrilirken fiil başa geçer: Gibt es ...?",
    },
    {
        "id": "a1-036",
        "module_id": "space_time",
        "prompt": '"Es ist halb acht." hangi saati anlatır?',
        "options": ["07:30", "08:30", "07:15"],
        "correct": "07:30",
        "explanation": "halb acht, sekize yarım saat var yani yedi buçuk demektir.",
    },
    {
        "id": "a1-037",
        "module_id": "space_time",
        "prompt": 'Hafta günü ile doğru kullanım hangisidir?',
        "options": ["am Dienstag", "um Dienstag", "in Dienstag"],
        "correct": "am Dienstag",
        "explanation": "Gün adıyla temel yapı am + gün biçimidir.",
    },
    {
        "id": "a1-038",
        "module_id": "space_time",
        "prompt": '"9\'dan 11\'e kadar" ifadesi hangisidir?',
        "options": ["von neun bis elf", "um neun bis elf", "zwischen neun bis elf"],
        "correct": "von neun bis elf",
        "explanation": "Saat aralığı vermenin temiz A1 kalıbı von ... bis ... biçimidir.",
    },
    {
        "id": "a1-039",
        "module_id": "space_time",
        "prompt": 'Ayrılabilen fiil içeren doğru cümle hangisidir?',
        "options": ["Ich stehe um 7 Uhr auf.", "Ich aufstehe um 7 Uhr.", "Ich stehe auf um 7 Uhr auf."],
        "correct": "Ich stehe um 7 Uhr auf.",
        "explanation": "Çekimli fiil ortada, ayrılan önek cümlenin sonunda yer alır.",
    },
    {
        "id": "a1-040",
        "module_id": "space_time",
        "prompt": '"Kurs ne zaman başlıyor?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Wann fängt der Kurs an?", "Wo fängt der Kurs an?", "Wann der Kurs fängt an?"],
        "correct": "Wann fängt der Kurs an?",
        "explanation": "Soru kelimesi + fiil + özne düzeni korunur; ayrılan parça sonda kalır.",
    },
    {
        "id": "a1-041",
        "module_id": "objects_orders",
        "prompt": '"Ben elmayı satın alıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich kaufe den Apfel.", "Ich kaufe der Apfel.", "Ich kaufe dem Apfel."],
        "correct": "Ich kaufe den Apfel.",
        "explanation": "Apfel maskulin nesnedir; Akkusativ olduğunda der -> den olur.",
    },
    {
        "id": "a1-042",
        "module_id": "objects_orders",
        "prompt": '"Bir kahve istiyorum / alıyorum." anlamına en uygun temel cümle hangisidir?',
        "options": ["Ich nehme einen Kaffee.", "Ich bin einen Kaffee.", "Ich habe der Kaffee."],
        "correct": "Ich nehme einen Kaffee.",
        "explanation": "Siparişte en doğal başlangıç kalıplarından biri Ich nehme ... yapısıdır.",
    },
    {
        "id": "a1-043",
        "module_id": "objects_orders",
        "prompt": '"Ben bir çorba sipariş ediyorum." cümlesi hangisidir?',
        "options": ["Ich bestelle eine Suppe.", "Ich bestelle einen Suppe.", "Ich nehme ein Suppe."],
        "correct": "Ich bestelle eine Suppe.",
        "explanation": "Suppe dişildir; eine Suppe kullanılır.",
    },
    {
        "id": "a1-044",
        "module_id": "objects_orders",
        "prompt": '"Suyunuz var mı?" sorusunun doğru biçimi hangisidir?',
        "options": ["Haben Sie Wasser?", "Sind Sie Wasser?", "Gibt Wasser Sie?"],
        "correct": "Haben Sie Wasser?",
        "explanation": "Kafe/restoran bağlamında elde bulunan şeyi sormanın temel kalıplarından biridir.",
    },
    {
        "id": "a1-045",
        "module_id": "objects_orders",
        "prompt": '"Çayın fiyatı ne kadar?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Was kostet der Tee?", "Wie alt ist der Tee?", "Wo kostet der Tee?"],
        "correct": "Was kostet der Tee?",
        "explanation": "Fiyat sormak için Was kostet ...? kalıbı kullanılır.",
    },
    {
        "id": "a1-046",
        "module_id": "objects_orders",
        "prompt": 'Sipariş verirken "Benim için bir pizza, lütfen." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Für mich eine Pizza, bitte.", "Ich für mich Pizza.", "Eine Pizza ist für mich bitte."],
        "correct": "Für mich eine Pizza, bitte.",
        "explanation": "Bu yapı restoranda kısa ve doğal sipariş kalıplarından biridir.",
    },
    {
        "id": "a1-047",
        "module_id": "objects_orders",
        "prompt": '"Bir salata ve bir su sipariş ediyorum." cümlesi hangisidir?',
        "options": ["Ich bestelle einen Salat und ein Wasser.", "Ich bestelle ein Salat und einen Wasser.", "Ich bestelle der Salat und das Wasser."],
        "correct": "Ich bestelle einen Salat und ein Wasser.",
        "explanation": "Salat maskulin olduğu için einen, Wasser nötr olduğu için ein kullanılır.",
    },
    {
        "id": "a1-048",
        "module_id": "objects_orders",
        "prompt": '"Den Lehrer" ifadesini bulduran doğru soru hangisidir?',
        "options": ["Wen suchst du?", "Was suchst du?", "Wo suchst du?"],
        "correct": "Wen suchst du?",
        "explanation": "Kişi nesnesi için wen sorulur.",
    },
    {
        "id": "a1-049",
        "module_id": "objects_orders",
        "prompt": '"Ich brauche einen Stuhl." cümlesinde Akkusativ nesne hangisidir?',
        "options": ["einen Stuhl", "Ich", "brauche"],
        "correct": "einen Stuhl",
        "explanation": "Fiilin doğrudan etkilediği nesne einen Stuhl ifadesidir.",
    },
    {
        "id": "a1-050",
        "module_id": "objects_orders",
        "prompt": 'Kafe diyalogunda en uygun cevap hangisidir?\nGarson: "Was möchten Sie?"',
        "options": ["Ich nehme einen Tee, bitte.", "Ich bin ein Tee.", "Wo ist ein Tee?"],
        "correct": "Ich nehme einen Tee, bitte.",
        "explanation": "Siparişe cevap verirken nesneyle birlikte doğal bir sipariş kalıbı gerekir.",
    },
    {
        "id": "a1-051",
        "module_id": "foundations",
        "prompt": '"öğretmen" anlamında kadın öğretmen için doğru kelime hangisidir?',
        "options": ["die Lehrerin", "der Lehrer", "das Lehrerin"],
        "correct": "die Lehrerin",
        "explanation": "Kadın öğretmen için die Lehrerin kullanılır.",
    },
    {
        "id": "a1-052",
        "module_id": "foundations",
        "prompt": '"Bu bir kitap." cümlesinin en doğal başlangıç seviyesi karşılığı hangisidir?',
        "options": ["Das ist ein Buch.", "Das Buch ist ein.", "Ich bin ein Buch."],
        "correct": "Das ist ein Buch.",
        "explanation": "Bir şeyi tanıtmanın temel kalıplarından biri Das ist ... yapısıdır.",
    },
    {
        "id": "a1-053",
        "module_id": "foundations",
        "prompt": '"sandalye" kelimesinin doğru artikel + isim biçimi hangisidir?',
        "options": ["der Stuhl", "die Stuhl", "das Stuhl"],
        "correct": "der Stuhl",
        "explanation": "Stuhl maskulin isimdir; der Stuhl olarak öğrenilir.",
    },
    {
        "id": "a1-054",
        "module_id": "foundations",
        "prompt": '"Bu çocuk sakin." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das Kind ist ruhig.", "Der Kind ist ruhig.", "Das Kind ruhig ist."],
        "correct": "Das Kind ist ruhig.",
        "explanation": "Kind nötr isimdir ve yüklem cümlesi sein ile kurulur.",
    },
    {
        "id": "a1-055",
        "module_id": "foundations",
        "prompt": 'Akşam birinden ayrılırken en uygun temel ifade hangisidir?',
        "options": ["Tschüss!", "Guten Morgen!", "Wie alt bist du?"],
        "correct": "Tschüss!",
        "explanation": "Tschüss günlük ve gayriresmî bir vedalaşma ifadesidir.",
    },
    {
        "id": "a1-056",
        "module_id": "foundations",
        "prompt": '"Bu masa büyük." cümlesi hangisidir?',
        "options": ["Der Tisch ist groß.", "Die Tisch ist groß.", "Der Tisch sind groß."],
        "correct": "Der Tisch ist groß.",
        "explanation": "Tisch maskulin isimdir; tekil özne ile ist kullanılır.",
    },
    {
        "id": "a1-057",
        "module_id": "foundations",
        "prompt": '"Onlar yorgun." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Sie sind müde.", "Sie ist müde.", "Ihr sind müde."],
        "correct": "Sie sind müde.",
        "explanation": "Onlar anlamındaki sie çoğuldur ve sind ile çekilir.",
    },
    {
        "id": "a1-058",
        "module_id": "foundations",
        "prompt": '"Adın ne?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Wie heißt du?", "Wer bist du?", "Wie alt du bist?"],
        "correct": "Wie heißt du?",
        "explanation": "İlk tanışmada ad sormanın temel kalıbı Wie heißt du? biçimidir.",
    },
    {
        "id": "a1-059",
        "module_id": "foundations",
        "prompt": '"Bu okul büyük." cümlesi hangisidir?',
        "options": ["Die Schule ist groß.", "Der Schule ist groß.", "Die Schule sind groß."],
        "correct": "Die Schule ist groß.",
        "explanation": "Schule dişil isimdir; tekil özne ile ist kullanılır.",
    },
    {
        "id": "a1-060",
        "module_id": "foundations",
        "prompt": 'Resmî bir selamlaşmada gün içinde en güvenli temel ifade hangisidir?',
        "options": ["Guten Tag!", "Hallo!", "Tschüss!"],
        "correct": "Guten Tag!",
        "explanation": "Guten Tag gün içinde daha resmî ve güvenli bir seçimdir.",
    },
    {
        "id": "a1-061",
        "module_id": "identity",
        "prompt": '"on dokuz" sayısının doğru Almancası hangisidir?',
        "options": ["neunzehn", "neunzig", "siebzehn"],
        "correct": "neunzehn",
        "explanation": "19 sayısı neunzehn olarak yazılır.",
    },
    {
        "id": "a1-062",
        "module_id": "identity",
        "prompt": '"Ben 18 yaşındayım." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bin 18 Jahre alt.", "Ich habe 18 Jahre alt.", "Ich bin 18 alt Jahre."],
        "correct": "Ich bin 18 Jahre alt.",
        "explanation": "Yaş cümlelerinde standart yapı Ich bin ... Jahre alt biçimidir.",
    },
    {
        "id": "a1-063",
        "module_id": "identity",
        "prompt": '"Sen nerelisin?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Woher kommst du?", "Wo kommst du?", "Wann kommst du?"],
        "correct": "Woher kommst du?",
        "explanation": "Köken sormak için Woher kullanılır.",
    },
    {
        "id": "a1-064",
        "module_id": "identity",
        "prompt": '"Ben Viyana\'dayım." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bin in Wien.", "Ich bin aus Wien.", "Ich komme Wien."],
        "correct": "Ich bin in Wien.",
        "explanation": "Bulunduğun yeri belirtirken in kullanılır.",
    },
    {
        "id": "a1-065",
        "module_id": "identity",
        "prompt": '"Biz Türkiye\'den geliyoruz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir kommen aus der Türkei.", "Wir kommen in der Türkei.", "Wir sind aus Türkei."],
        "correct": "Wir kommen aus der Türkei.",
        "explanation": "die Türkei artikel aldığı için aus der Türkei kullanılır.",
    },
    {
        "id": "a1-066",
        "module_id": "identity",
        "prompt": '"O İspanyol." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Er ist spanisch.", "Er ist Spanien.", "Er spanisch ist."],
        "correct": "Er ist spanisch.",
        "explanation": "Milliyet bilgisi burada sıfat gibi kullanılır: spanisch.",
    },
    {
        "id": "a1-067",
        "module_id": "identity",
        "prompt": 'Doğru soru düzeni hangisidir?',
        "options": ["Wann arbeitest du?", "Wann du arbeitest?", "Du wann arbeitest?"],
        "correct": "Wann arbeitest du?",
        "explanation": "Soru kelimesinden sonra çekimli fiil gelir.",
    },
    {
        "id": "a1-068",
        "module_id": "identity",
        "prompt": '"nerede" anlamına gelen soru kelimesi hangisidir?',
        "options": ["wo", "wer", "wie"],
        "correct": "wo",
        "explanation": "wo yer sorar; wer kişi, wie ise biçim/durum sorar.",
    },
    {
        "id": "a1-069",
        "module_id": "identity",
        "prompt": '"Ben Almanya\'danım ve Berlin\'deyim." cümlesine en yakın doğru seçenek hangisidir?',
        "options": ["Ich bin aus Deutschland und ich bin in Berlin.", "Ich bin in Deutschland und aus Berlin.", "Ich komme Berlin und in Deutschland."],
        "correct": "Ich bin aus Deutschland und ich bin in Berlin.",
        "explanation": "Köken ve bulunulan yer iki ayrı yapıyla ifade edilir: aus ve in.",
    },
    {
        "id": "a1-070",
        "module_id": "identity",
        "prompt": '"Kaç yaşında?" anlamına en uygun soru hangisidir?',
        "options": ["Wie alt ist er?", "Wie heißt er?", "Was arbeitet er?"],
        "correct": "Wie alt ist er?",
        "explanation": "Üçüncü tekil kişi için yaş sorusu Wie alt ist er/sie? biçiminde kurulur.",
    },
    {
        "id": "a1-071",
        "module_id": "daily_life",
        "prompt": '"Sizin bir eviniz var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ihr habt ein Haus.", "Ihr seid ein Haus.", "Sie habt ein Haus."],
        "correct": "Ihr habt ein Haus.",
        "explanation": "ihr ile haben fiili habt olur.",
    },
    {
        "id": "a1-072",
        "module_id": "daily_life",
        "prompt": '"onun telefonu" ifadesinin doğru biçimi hangisidir?',
        "options": ["sein Handy", "er Handy", "ist Handy"],
        "correct": "sein Handy",
        "explanation": "Aitlik, isimden önce gelen iyelik sözüyle kurulur: sein Handy.",
    },
    {
        "id": "a1-073",
        "module_id": "daily_life",
        "prompt": '"Bu bizim öğretmenimiz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist unser Lehrer.", "Wir haben unser Lehrer.", "Das ist wir Lehrer."],
        "correct": "Das ist unser Lehrer.",
        "explanation": "Tanıtma yapısında Das ist ... kullanılır; iyelik sözü nesneden önce gelir.",
    },
    {
        "id": "a1-074",
        "module_id": "daily_life",
        "prompt": '"Ben her gün çalışıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich arbeite jeden Tag.", "Ich jeden Tag arbeite.", "Ich bin jeden Tag arbeite."],
        "correct": "Ich arbeite jeden Tag.",
        "explanation": "Düz cümlede özne + çekimli fiil + zaman tamamlayıcısı sıralaması korunur.",
    },
    {
        "id": "a1-075",
        "module_id": "daily_life",
        "prompt": '"Saat dokuzda kahvaltı yapıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich frühstücke um neun Uhr.", "Ich frühstücke am neun Uhr.", "Um neun Uhr ich frühstücke."],
        "correct": "Ich frühstücke um neun Uhr.",
        "explanation": "Saat ifadesi için um kullanılır; düz cümlede fiil özneden sonra gelir.",
    },
    {
        "id": "a1-076",
        "module_id": "daily_life",
        "prompt": 'Zaman ifadesi başta olduğunda doğru cümle hangisidir?',
        "options": ["Am Montag lerne ich Deutsch.", "Am Montag ich lerne Deutsch.", "Ich am Montag lerne Deutsch."],
        "correct": "Am Montag lerne ich Deutsch.",
        "explanation": "Zaman ifadesi başta olsa da çekimli fiil ikinci sırada kalır.",
    },
    {
        "id": "a1-077",
        "module_id": "daily_life",
        "prompt": '"Akşamları evdeyiz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Abends sind wir zu Hause.", "Abends wir sind zu Hause.", "Wir zu Hause sind abends."],
        "correct": "Abends sind wir zu Hause.",
        "explanation": "Zaman ifadesi başta olduğunda fiil yine ikinci sırada kalır.",
    },
    {
        "id": "a1-078",
        "module_id": "daily_life",
        "prompt": '"Benim bir çantam yok." cümlesi hangisidir?',
        "options": ["Ich habe keine Tasche.", "Ich habe nicht Tasche.", "Ich bin keine Tasche."],
        "correct": "Ich habe keine Tasche.",
        "explanation": "Dişil isimlerde olumsuzluk keine ile kurulur.",
    },
    {
        "id": "a1-079",
        "module_id": "daily_life",
        "prompt": '"Bizim bir masamız var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir haben einen Tisch.", "Wir haben ein Tisch.", "Wir sind einen Tisch."],
        "correct": "Wir haben einen Tisch.",
        "explanation": "Tisch maskulin isimdir; nesne biçiminde einen Tisch kullanılır.",
    },
    {
        "id": "a1-080",
        "module_id": "daily_life",
        "prompt": '"Sabahları ne yapıyorsun?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Was machst du morgens?", "Wann machst du morgens?", "Wo machst du morgens?"],
        "correct": "Was machst du morgens?",
        "explanation": "İçerik/eylem sorulduğu için was kullanılır.",
    },
    {
        "id": "a1-081",
        "module_id": "space_time",
        "prompt": '\"Bu bir oda.\" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist ein Zimmer.", "Das ist der Zimmer.", "Es gibt den Zimmer."],
        "correct": "Das ist ein Zimmer.",
        "explanation": "Yeni tanıtılan nesne için belirsiz artikel kullanılır: ein Zimmer.",
    },
    {
        "id": "a1-082",
        "module_id": "space_time",
        "prompt": '\"Mutfak yok.\" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Es gibt keine Küche.", "Es gibt nicht Küche.", "Es ist keine Küche."],
        "correct": "Es gibt keine Küche.",
        "explanation": "Var-yok anlatımında isim olumsuzluğu keine Küche ile kurulur.",
    },
    {
        "id": "a1-083",
        "module_id": "space_time",
        "prompt": '\"Masa burada.\" cümlesi hangisidir?',
        "options": ["Der Tisch ist hier.", "Der Tisch ist aus hier.", "Hier der Tisch ist."],
        "correct": "Der Tisch ist hier.",
        "explanation": "Kısa yer bildiriminde hier ve dort doğrudan kullanılabilir.",
    },
    {
        "id": "a1-084",
        "module_id": "space_time",
        "prompt": '\"Banyo şurada.\" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das Bad ist dort.", "Das Bad dort ist.", "Dort ist das Bad?"],
        "correct": "Das Bad ist dort.",
        "explanation": "Yer bildirirken yüklem cümlesi Das Bad ist dort şeklinde kurulur.",
    },
    {
        "id": "a1-085",
        "module_id": "space_time",
        "prompt": '\"Saat çeyrek geçiyor.\" ifadesinin doğru Almancası hangisidir?',
        "options": ["Es ist Viertel nach drei.", "Es ist Viertel vor drei.", "Es ist halb drei."],
        "correct": "Es ist Viertel nach drei.",
        "explanation": "Viertel nach ... saatten çeyrek geçeyi anlatır.",
    },
    {
        "id": "a1-086",
        "module_id": "space_time",
        "prompt": '\"Saat dörde çeyrek var.\" ifadesinin doğru Almancası hangisidir?',
        "options": ["Es ist Viertel vor vier.", "Es ist Viertel nach vier.", "Es ist halb vier."],
        "correct": "Es ist Viertel vor vier.",
        "explanation": "Viertel vor ... ilgili saatten çeyrek önceyi anlatır.",
    },
    {
        "id": "a1-087",
        "module_id": "space_time",
        "prompt": '\"Hafta sonu çalışıyorum.\" cümlesi hangisidir?',
        "options": ["Ich arbeite am Wochenende.", "Ich arbeite um Wochenende.", "Ich arbeite Wochenende am."],
        "correct": "Ich arbeite am Wochenende.",
        "explanation": "Hafta sonu ifadesi am Wochenende kalıbıyla kullanılır.",
    },
    {
        "id": "a1-088",
        "module_id": "space_time",
        "prompt": '\"Pazartesiden cumaya kadar\" ifadesine en uygun seçenek hangisidir?',
        "options": ["von Montag bis Freitag", "am Montag bis Freitag", "um Montag bis Freitag"],
        "correct": "von Montag bis Freitag",
        "explanation": "Gün aralığı vermek için von ... bis ... kullanılır.",
    },
    {
        "id": "a1-089",
        "module_id": "space_time",
        "prompt": '\"Ben saat yedide kalkıyorum.\" cümlesi hangisidir?',
        "options": ["Ich stehe um sieben Uhr auf.", "Ich aufstehe um sieben Uhr.", "Ich stehe auf um sieben Uhr auf."],
        "correct": "Ich stehe um sieben Uhr auf.",
        "explanation": "Ayrılabilen fiilde çekimli kısım ortada, önek sonda kalır.",
    },
    {
        "id": "a1-090",
        "module_id": "space_time",
        "prompt": '\"Kurs ne zaman bitiyor?\" sorusunun doğru karşılığı hangisidir?',
        "options": ["Wann hört der Kurs auf?", "Wann der Kurs hört auf?", "Wo hört der Kurs auf?"],
        "correct": "Wann hört der Kurs auf?",
        "explanation": "Soru kelimesinden sonra çekimli fiil gelir, ayrılan parça sonda kalır.",
    },
    {
        "id": "a1-091",
        "module_id": "objects_orders",
        "prompt": '\"Ben bir çay sipariş ediyorum.\" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bestelle einen Tee.", "Ich bestelle ein Tee.", "Ich bestelle der Tee."],
        "correct": "Ich bestelle einen Tee.",
        "explanation": "Tee maskulin nesnedir; siparişte einen Tee kullanılır.",
    },
    {
        "id": "a1-092",
        "module_id": "objects_orders",
        "prompt": '\"Bir su alıyorum.\" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich nehme ein Wasser.", "Ich nehme einen Wasser.", "Ich nehme eine Wasser."],
        "correct": "Ich nehme ein Wasser.",
        "explanation": "Wasser nötr isimdir; ein Wasser kullanılır.",
    },
    {
        "id": "a1-093",
        "module_id": "objects_orders",
        "prompt": '\"Ben pizza istemiyorum.\" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich nehme keine Pizza.", "Ich nehme keinen Pizza.", "Ich nehme nicht Pizza."],
        "correct": "Ich nehme keine Pizza.",
        "explanation": "Pizza dişildir; isim olumsuzluğu keine Pizza ile kurulur.",
    },
    {
        "id": "a1-094",
        "module_id": "objects_orders",
        "prompt": '\"Garsonu görüyorum.\" cümlesi hangisidir?',
        "options": ["Ich sehe den Kellner.", "Ich sehe der Kellner.", "Ich sehe dem Kellner."],
        "correct": "Ich sehe den Kellner.",
        "explanation": "Kellner maskulin nesnedir; sehen ile den Kellner kullanılır.",
    },
    {
        "id": "a1-095",
        "module_id": "objects_orders",
        "prompt": '\"Menüyü okuyorum.\" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich lese die Speisekarte.", "Ich lese den Speisekarte.", "Ich lese das Speisekarte."],
        "correct": "Ich lese die Speisekarte.",
        "explanation": "Speisekarte dişil nesnedir; die biçimi korunur.",
    },
    {
        "id": "a1-096",
        "module_id": "objects_orders",
        "prompt": '\"Bir kahve ve bir çay alıyoruz.\" cümlesi hangisidir?',
        "options": ["Wir nehmen einen Kaffee und einen Tee.", "Wir nehmen ein Kaffee und ein Tee.", "Wir sind einen Kaffee und einen Tee."],
        "correct": "Wir nehmen einen Kaffee und einen Tee.",
        "explanation": "Her iki kelime de maskulin olduğundan einen biçimi gerekir.",
    },
    {
        "id": "a1-097",
        "module_id": "objects_orders",
        "prompt": '\"Bir salata istiyorum.\" anlamına en uygun kısa sipariş hangisidir?',
        "options": ["Für mich einen Salat, bitte.", "Ich bin einen Salat.", "Der Salat, ich bitte."],
        "correct": "Für mich einen Salat, bitte.",
        "explanation": "Kısa ve doğal sipariş kalıplarından biri Für mich ... , bitte yapısıdır.",
    },
    {
        "id": "a1-098",
        "module_id": "objects_orders",
        "prompt": '\"Hesap lütfen, teşekkürler.\" ifadesine en yakın doğru seçenek hangisidir?',
        "options": ["Die Rechnung, bitte. Danke.", "Was kostet die Rechnung?", "Ich nehme die Rechnung."],
        "correct": "Die Rechnung, bitte. Danke.",
        "explanation": "Restoran kapanışında hesap istemenin temel kalıbı budur.",
    },
    {
        "id": "a1-099",
        "module_id": "objects_orders",
        "prompt": '\"Neyi satın alıyorsun?\" sorusunun doğru Almancası hangisidir?',
        "options": ["Was kaufst du?", "Wen kaufst du?", "Wo kaufst du?"],
        "correct": "Was kaufst du?",
        "explanation": "Cansız nesne sorulduğunda was kullanılır.",
    },
    {
        "id": "a1-100",
        "module_id": "objects_orders",
        "prompt": '\"Ben bir sandalyeye ihtiyacım var.\" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich brauche einen Stuhl.", "Ich brauche ein Stuhl.", "Ich bin einen Stuhl."],
        "correct": "Ich brauche einen Stuhl.",
        "explanation": "Stuhl maskulin nesnedir; brauchen ile einen Stuhl gerekir.",
    },
    {
        "id": "a1-101",
        "module_id": "foundations",
        "prompt": '"ev" kelimesinin doğru artikel + isim biçimi hangisidir?',
        "options": ["das Haus", "der Haus", "die Haus"],
        "correct": "das Haus",
        "explanation": "Haus nötr isimdir; das Haus olarak öğrenilir.",
    },
    {
        "id": "a1-102",
        "module_id": "foundations",
        "prompt": '"Bu öğretmen Arda." cümlesine en uygun seçenek hangisidir?',
        "options": ["Das ist Lehrer Arda.", "Das ist der Lehrer Arda.", "Ich bin Lehrer Arda."],
        "correct": "Das ist der Lehrer Arda.",
        "explanation": "Bir kişiyi tanıtırken Das ist ... kalıbı kullanılabilir; Lehrer artikeliyle gelir.",
    },
    {
        "id": "a1-103",
        "module_id": "foundations",
        "prompt": '"İyi akşamlar!" ifadesinin doğru Almancası hangisidir?',
        "options": ["Guten Abend!", "Guten Morgen!", "Gute Nacht!"],
        "correct": "Guten Abend!",
        "explanation": "Akşam saatlerinde selamlaşma için Guten Abend kullanılır.",
    },
    {
        "id": "a1-104",
        "module_id": "foundations",
        "prompt": '"Biz öğretmeniz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir sind Lehrer.", "Wir seid Lehrer.", "Wir sind ein Lehrer."],
        "correct": "Wir sind Lehrer.",
        "explanation": "wir ile sein fiili sind olur; meslek bilgisi yalın biçimde verilebilir.",
    },
    {
        "id": "a1-105",
        "module_id": "foundations",
        "prompt": '"Onlar öğrenciler." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Sie sind Schüler.", "Sie ist Schüler.", "Ihr seid Schüler."],
        "correct": "Sie sind Schüler.",
        "explanation": "Onlar anlamındaki sie çoğuldur ve sind ile çekilir.",
    },
    {
        "id": "a1-106",
        "module_id": "foundations",
        "prompt": '\"Wie heißt du?\" sorusuna uygun cevap hangisidir?',
        "options": ["Ich heiße Mert.", "Ich bin aus Bonn.", "Ich habe ein Buch."],
        "correct": "Ich heiße Mert.",
        "explanation": "Ad sorusuna en doğrudan cevap Ich heiße ... yapısıdır.",
    },
    {
        "id": "a1-107",
        "module_id": "foundations",
        "prompt": '"Bu kadın öğretmen." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Die Frau ist Lehrerin.", "Der Frau ist Lehrerin.", "Die Frau sind Lehrerin."],
        "correct": "Die Frau ist Lehrerin.",
        "explanation": "Frau dişil isimdir; tekil özne ile ist kullanılır.",
    },
    {
        "id": "a1-108",
        "module_id": "foundations",
        "prompt": '\"Merhaba, benim adım Deniz.\" cümlesine en uygun seçenek hangisidir?',
        "options": ["Hallo, ich heiße Deniz.", "Hallo, ich bin aus Deniz.", "Tschüss, ich heiße Deniz."],
        "correct": "Hallo, ich heiße Deniz.",
        "explanation": "Selamlaşma ve tanışma tek cümlede böyle birleşir.",
    },
    {
        "id": "a1-109",
        "module_id": "foundations",
        "prompt": '"Biz yorgunuz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir sind müde.", "Wir seid müde.", "Wir bin müde."],
        "correct": "Wir sind müde.",
        "explanation": "wir ile sein fiili sind olur.",
    },
    {
        "id": "a1-110",
        "module_id": "foundations",
        "prompt": '"Bu bir lamba." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist eine Lampe.", "Das ist einen Lampe.", "Das ist der Lampe."],
        "correct": "Das ist eine Lampe.",
        "explanation": "Lampe dişildir; yeni nesne tanıtılırken eine Lampe kullanılır.",
    },
    {
        "id": "a1-111",
        "module_id": "identity",
        "prompt": '"on iki" sayısının doğru Almancası hangisidir?',
        "options": ["zwölf", "zwanzig", "zwei"],
        "correct": "zwölf",
        "explanation": "12 sayısı Almancada zwölf olarak yazılır.",
    },
    {
        "id": "a1-112",
        "module_id": "identity",
        "prompt": '"O 30 yaşında." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Er ist 30 Jahre alt.", "Er hat 30 Jahre alt.", "Er ist 30 alt Jahre."],
        "correct": "Er ist 30 Jahre alt.",
        "explanation": "Yaş cümlesi sein fiiliyle kurulur.",
    },
    {
        "id": "a1-113",
        "module_id": "identity",
        "prompt": '"Biz Viyana\'danız." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir sind aus Wien.", "Wir sind in Wien.", "Wir kommen Wien."],
        "correct": "Wir sind aus Wien.",
        "explanation": "Köken belirtirken aus kullanılır.",
    },
    {
        "id": "a1-114",
        "module_id": "identity",
        "prompt": "\"Sen Almanya'da mısın?\" sorusunun doğru karşılığı hangisidir?",
        "options": ["Bist du in Deutschland?", "Bist du aus Deutschland?", "Woher bist du Deutschland?"],
        "correct": "Bist du in Deutschland?",
        "explanation": "Bulunulan yeri sormak için in kullanılır; soru olduğu için fiil başa geçer.",
    },
    {
        "id": "a1-115",
        "module_id": "identity",
        "prompt": '"Onlar Türk." cümlesinin en uygun karşılığı hangisidir?',
        "options": ["Sie sind türkisch.", "Sie sind Türkei.", "Sie heißen türkisch."],
        "correct": "Sie sind türkisch.",
        "explanation": "Milliyet burada sıfat gibi kullanılır.",
    },
    {
        "id": "a1-116",
        "module_id": "identity",
        "prompt": '\"Nerede yaşıyorsun?\" sorusunun doğru Almancası hangisidir?',
        "options": ["Wo wohnst du?", "Woher wohnst du?", "Wie wohnst du?"],
        "correct": "Wo wohnst du?",
        "explanation": "Yer sormak için wo kullanılır.",
    },
    {
        "id": "a1-117",
        "module_id": "identity",
        "prompt": '\"Ne yapıyorsun / ne iş yapıyorsun?\" sorusuna en yakın seçenek hangisidir?',
        "options": ["Was machst du?", "Wer machst du?", "Wie alt machst du?"],
        "correct": "Was machst du?",
        "explanation": "Genel eylem veya iş sormak için was kullanılır.",
    },
    {
        "id": "a1-118",
        "module_id": "identity",
        "prompt": '"Bugün ne öğreniyorsun?" sorusunun doğru dizilişi hangisidir?',
        "options": ["Was lernst du heute?", "Was du lernst heute?", "Du was lernst heute?"],
        "correct": "Was lernst du heute?",
        "explanation": "Soru kelimesinden sonra çekimli fiil gelir.",
    },
    {
        "id": "a1-119",
        "module_id": "identity",
        "prompt": '"Ben Avusturya\'danım." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich komme aus Österreich.", "Ich komme in Österreich.", "Ich bin Österreich."],
        "correct": "Ich komme aus Österreich.",
        "explanation": "Österreich genel kullanımda artikelsiz ülke adıdır; aus Österreich denir.",
    },
    {
        "id": "a1-120",
        "module_id": "identity",
        "prompt": '"Sen kimsin?" sorusunun doğru Almancası hangisidir?',
        "options": ["Wer bist du?", "Wo bist du?", "Wie bist du?"],
        "correct": "Wer bist du?",
        "explanation": "Kişi sormak için wer kullanılır.",
    },
    {
        "id": "a1-121",
        "module_id": "daily_life",
        "prompt": '"Benim bir telefonum var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich habe ein Handy.", "Ich bin ein Handy.", "Ich habe der Handy."],
        "correct": "Ich habe ein Handy.",
        "explanation": "Sahiplik cümlesi haben ile kurulur; Handy nötr isimdir.",
    },
    {
        "id": "a1-122",
        "module_id": "daily_life",
        "prompt": '"senin kitabın" ifadesinin doğru biçimi hangisidir?',
        "options": ["dein Buch", "du Buch", "bist Buch"],
        "correct": "dein Buch",
        "explanation": "İyelik, isimden önce gelen dein ile kurulur.",
    },
    {
        "id": "a1-123",
        "module_id": "daily_life",
        "prompt": '"Bu bizim evimiz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist unser Haus.", "Wir haben unser Haus.", "Das ist wir Haus."],
        "correct": "Das ist unser Haus.",
        "explanation": "Tanıtma yapısında Das ist ... kalıbı kullanılabilir.",
    },
    {
        "id": "a1-124",
        "module_id": "daily_life",
        "prompt": '"Ben her sabah erken kalkıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich stehe jeden Morgen früh auf.", "Ich jeden Morgen früh aufstehe.", "Jeden Morgen ich stehe früh auf."],
        "correct": "Ich stehe jeden Morgen früh auf.",
        "explanation": "Düz cümlede özne + çekimli fiil + diğer ögeler + ayrılan önek sırası korunur.",
    },
    {
        "id": "a1-125",
        "module_id": "daily_life",
        "prompt": '"Saat yedide okula gidiyoruz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir gehen um sieben Uhr zur Schule.", "Wir gehen am sieben Uhr zur Schule.", "Um sieben Uhr wir gehen zur Schule."],
        "correct": "Wir gehen um sieben Uhr zur Schule.",
        "explanation": "Saat ifadelerinde um kullanılır.",
    },
    {
        "id": "a1-126",
        "module_id": "daily_life",
        "prompt": 'Zaman ifadesi başta olan doğru cümle hangisidir?',
        "options": ["Morgens trinkt sie Tee.", "Morgens sie trinkt Tee.", "Sie morgens trinkt Tee."],
        "correct": "Morgens trinkt sie Tee.",
        "explanation": "Zaman ifadesi başta olduğunda fiil ikinci sıraya gelir.",
    },
    {
        "id": "a1-127",
        "module_id": "daily_life",
        "prompt": '"Onların bir arabası yok." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Sie haben kein Auto.", "Sie haben keine Auto.", "Sie sind kein Auto."],
        "correct": "Sie haben kein Auto.",
        "explanation": "Auto nötr isimdir; olumsuz biçimi kein Auto olur.",
    },
    {
        "id": "a1-128",
        "module_id": "daily_life",
        "prompt": '"Biz akşamları müzik dinliyoruz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Abends hören wir Musik.", "Abends wir hören Musik.", "Wir abends hören Musik."],
        "correct": "Abends hören wir Musik.",
        "explanation": "Zaman ifadesi başa geldiğinde fiil ikinci sırada kalır.",
    },
    {
        "id": "a1-129",
        "module_id": "daily_life",
        "prompt": '"Benim kız kardeşim var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich habe eine Schwester.", "Ich bin eine Schwester.", "Ich habe Schwester."],
        "correct": "Ich habe eine Schwester.",
        "explanation": "Sahiplik haben ile kurulur; Schwester dişil isimdir.",
    },
    {
        "id": "a1-130",
        "module_id": "daily_life",
        "prompt": '"Ne zaman Almanca çalışıyorsun?" sorusunun doğru Almancası hangisidir?',
        "options": ["Wann lernst du Deutsch?", "Wo lernst du Deutsch?", "Wer lernst du Deutsch?"],
        "correct": "Wann lernst du Deutsch?",
        "explanation": "Zaman sormak için wann kullanılır.",
    },
    {
        "id": "a1-131",
        "module_id": "space_time",
        "prompt": '"Bu bir mutfak." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist eine Küche.", "Das ist ein Küche.", "Es gibt Küche."],
        "correct": "Das ist eine Küche.",
        "explanation": "Küche dişil isimdir; bir mekân tanıtılırken eine Küche kullanılır.",
    },
    {
        "id": "a1-132",
        "module_id": "space_time",
        "prompt": '"Masada bir lamba yok." anlamına en yakın doğru seçenek hangisidir?',
        "options": ["Es gibt keine Lampe.", "Es gibt nicht Lampe.", "Die Lampe ist kein."],
        "correct": "Es gibt keine Lampe.",
        "explanation": "Dişil isim olumsuzluğunda keine kullanılır.",
    },
    {
        "id": "a1-133",
        "module_id": "space_time",
        "prompt": '"Anahtar burada." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Der Schlüssel ist hier.", "Der Schlüssel ist aus hier.", "Hier der Schlüssel ist."],
        "correct": "Der Schlüssel ist hier.",
        "explanation": "Kısa yer bildiriminde hier doğal biçimde kullanılır.",
    },
    {
        "id": "a1-134",
        "module_id": "space_time",
        "prompt": '"Odada bir masa var mı?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Gibt es einen Tisch im Zimmer?", "Es gibt einen Tisch im Zimmer?", "Wo ist einen Tisch im Zimmer?"],
        "correct": "Gibt es einen Tisch im Zimmer?",
        "explanation": "Var mı sorusunda fiil başa geçer: Gibt es ...?",
    },
    {
        "id": "a1-135",
        "module_id": "space_time",
        "prompt": '"Saat beşi çeyrek geçiyor." ifadesinin doğru Almancası hangisidir?',
        "options": ["Es ist Viertel nach fünf.", "Es ist Viertel vor fünf.", "Es ist halb fünf."],
        "correct": "Es ist Viertel nach fünf.",
        "explanation": "Viertel nach ... saatten çeyrek geçeyi anlatır.",
    },
    {
        "id": "a1-136",
        "module_id": "space_time",
        "prompt": '"Saat bire çeyrek var." ifadesinin doğru Almancası hangisidir?',
        "options": ["Es ist Viertel vor eins.", "Es ist Viertel nach eins.", "Es ist halb eins."],
        "correct": "Es ist Viertel vor eins.",
        "explanation": "Viertel vor ... ilgili saatten çeyrek önceyi anlatır.",
    },
    {
        "id": "a1-137",
        "module_id": "space_time",
        "prompt": '"Ben salı günü evdeyim." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bin am Dienstag zu Hause.", "Ich bin um Dienstag zu Hause.", "Ich am Dienstag bin zu Hause."],
        "correct": "Ich bin am Dienstag zu Hause.",
        "explanation": "Gün adıyla temel kullanım am + gün biçimindedir.",
    },
    {
        "id": "a1-138",
        "module_id": "space_time",
        "prompt": '"Pazartesiden cumaya kadar çalışıyoruz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir arbeiten von Montag bis Freitag.", "Wir arbeiten am Montag bis Freitag.", "Wir arbeiten um Montag bis Freitag."],
        "correct": "Wir arbeiten von Montag bis Freitag.",
        "explanation": "Gün aralığı kurarken von ... bis ... kullanılır.",
    },
    {
        "id": "a1-139",
        "module_id": "space_time",
        "prompt": '"O saat sekizde arıyor." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Er ruft um acht Uhr an.", "Er anruft um acht Uhr.", "Er ruft an um acht Uhr an."],
        "correct": "Er ruft um acht Uhr an.",
        "explanation": "Ayrılabilen fiilde çekimli kısım önde, önek sonda kalır.",
    },
    {
        "id": "a1-140",
        "module_id": "space_time",
        "prompt": '"Ders ne zaman başlıyor?" sorusunun ayrılabilen fiilli doğru karşılığı hangisidir?',
        "options": ["Wann fängt der Unterricht an?", "Wann der Unterricht fängt an?", "Wo fängt der Unterricht an?"],
        "correct": "Wann fängt der Unterricht an?",
        "explanation": "Soru kelimesinden sonra çekimli fiil gelir; ayrılan parça sonda kalır.",
    },
    {
        "id": "a1-141",
        "module_id": "objects_orders",
        "prompt": '"Ben bir kahve ve bir su sipariş ediyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bestelle einen Kaffee und ein Wasser.", "Ich bestelle ein Kaffee und einen Wasser.", "Ich bin einen Kaffee und ein Wasser."],
        "correct": "Ich bestelle einen Kaffee und ein Wasser.",
        "explanation": "Kaffee maskulin, Wasser nötrdür; doğru nesne biçimleri birlikte kullanılır.",
    },
    {
        "id": "a1-142",
        "module_id": "objects_orders",
        "prompt": '"Ben çorba istemiyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich nehme keine Suppe.", "Ich nehme keinen Suppe.", "Ich nehme nicht Suppe."],
        "correct": "Ich nehme keine Suppe.",
        "explanation": "Suppe dişildir; isim olumsuzluğu keine Suppe ile kurulur.",
    },
    {
        "id": "a1-143",
        "module_id": "objects_orders",
        "prompt": '"Garson menüyü getiriyor." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Der Kellner bringt die Speisekarte.", "Der Kellner bringt den Speisekarte.", "Der Kellner bringt das Speisekarte."],
        "correct": "Der Kellner bringt die Speisekarte.",
        "explanation": "Speisekarte dişil nesnedir; die biçimi kullanılır.",
    },
    {
        "id": "a1-144",
        "module_id": "objects_orders",
        "prompt": '"Ben salatayı arıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich suche den Salat.", "Ich suche der Salat.", "Ich suche dem Salat."],
        "correct": "Ich suche den Salat.",
        "explanation": "Salat maskulin nesnedir; Akkusativ olduğunda den Salat olur.",
    },
    {
        "id": "a1-145",
        "module_id": "objects_orders",
        "prompt": '"Ben kitabı okuyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich lese das Buch.", "Ich lese den Buch.", "Ich lese dem Buch."],
        "correct": "Ich lese das Buch.",
        "explanation": "Buch nötr nesnedir; das Buch biçimi korunur.",
    },
    {
        "id": "a1-146",
        "module_id": "objects_orders",
        "prompt": '\"den Kellner\" ifadesini bulduran doğru soru hangisidir?',
        "options": ["Wen siehst du?", "Was siehst du?", "Wo siehst du?"],
        "correct": "Wen siehst du?",
        "explanation": "Kişi nesnesi için wen kullanılır.",
    },
    {
        "id": "a1-147",
        "module_id": "objects_orders",
        "prompt": '"Salat ne kadar?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Was kostet der Salat?", "Wie kostet der Salat?", "Wo kostet der Salat?"],
        "correct": "Was kostet der Salat?",
        "explanation": "Fiyat sormak için Was kostet ...? kalıbı gerekir.",
    },
    {
        "id": "a1-148",
        "module_id": "objects_orders",
        "prompt": '"Bir çay daha?" teklifine uygun kısa red cevabı hangisidir?',
        "options": ["Nein, danke.", "Die Rechnung, bitte.", "Ich bin Tee."],
        "correct": "Nein, danke.",
        "explanation": "Kibarca reddetmenin kısa ve doğal yolu budur.",
    },
    {
        "id": "a1-149",
        "module_id": "objects_orders",
        "prompt": '"Benim için bir kahve, lütfen." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Für mich einen Kaffee, bitte.", "Für mich ein Kaffee, bitte.", "Ich für mich einen Kaffee."],
        "correct": "Für mich einen Kaffee, bitte.",
        "explanation": "Kısa sipariş kalıbında maskulin nesne için einen gerekir.",
    },
    {
        "id": "a1-150",
        "module_id": "objects_orders",
        "prompt": '"Ben hesabı istiyorum." anlamına en yakın doğru seçenek hangisidir?',
        "options": ["Die Rechnung, bitte.", "Was kostet die Rechnung?", "Ich brauche das Wasser."],
        "correct": "Die Rechnung, bitte.",
        "explanation": "Restoran kapanışında hesap istemenin en doğal kalıplarından biridir.",
    },
    {
        "id": "a1-151",
        "module_id": "foundations",
        "prompt": '"masa" kelimesinin doğru artikel + isim biçimi hangisidir?',
        "options": ["der Tisch", "die Tisch", "das Tisch"],
        "correct": "der Tisch",
        "explanation": "Tisch maskulin isimdir; der Tisch olarak öğrenilir.",
    },
    {
        "id": "a1-152",
        "module_id": "foundations",
        "prompt": '"Bu bir okul." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist eine Schule.", "Das ist ein Schule.", "Das ist der Schule."],
        "correct": "Das ist eine Schule.",
        "explanation": "Schule dişil isimdir; yeni tanıtımda eine Schule kullanılır.",
    },
    {
        "id": "a1-153",
        "module_id": "foundations",
        "prompt": '"Siz yorgunsunuz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Sie sind müde.", "Sie ist müde.", "Ihr sind müde."],
        "correct": "Sie sind müde.",
        "explanation": "Resmî hitaptaki Sie ile sind kullanılır.",
    },
    {
        "id": "a1-154",
        "module_id": "foundations",
        "prompt": '"Ben öğretmenim." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bin Lehrer.", "Ich heiße Lehrer.", "Ich habe Lehrer."],
        "correct": "Ich bin Lehrer.",
        "explanation": "Meslek bilgisi başlangıç düzeyinde sein ile verilir.",
    },
    {
        "id": "a1-155",
        "module_id": "foundations",
        "prompt": '"Bu kitap yeni." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das Buch ist neu.", "Der Buch ist neu.", "Das Buch sind neu."],
        "correct": "Das Buch ist neu.",
        "explanation": "Buch nötr isimdir; tekil yüklem cümlesi ist ile kurulur.",
    },
    {
        "id": "a1-156",
        "module_id": "foundations",
        "prompt": 'Günün içinde nötr ve güvenli bir selamlaşma için en uygun ifade hangisidir?',
        "options": ["Guten Tag!", "Gute Nacht!", "Noch etwas?"],
        "correct": "Guten Tag!",
        "explanation": "Guten Tag gün içinde en güvenli resmî/yarı resmî selamlaşma kalıbıdır.",
    },
    {
        "id": "a1-157",
        "module_id": "foundations",
        "prompt": '"Bu Bayan Demir." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist Frau Demir.", "Die ist Frau Demir.", "Das Frau Demir ist."],
        "correct": "Das ist Frau Demir.",
        "explanation": "Birini tanıtırken Das ist ... kalıbı kullanılır.",
    },
    {
        "id": "a1-158",
        "module_id": "foundations",
        "prompt": '\"hoşça kal\" anlamına gelen günlük ifade hangisidir?',
        "options": ["Tschüss!", "Guten Abend!", "Wie heißt du?"],
        "correct": "Tschüss!",
        "explanation": "Tschüss günlük vedalaşma ifadesidir.",
    },
    {
        "id": "a1-159",
        "module_id": "foundations",
        "prompt": '"Bu çocuk sakin." cümlesindeki doğru özne hangisidir?',
        "options": ["das Kind", "der Kind", "die Kind"],
        "correct": "das Kind",
        "explanation": "Kind nötr isimdir; das Kind olarak kullanılır.",
    },
    {
        "id": "a1-160",
        "module_id": "foundations",
        "prompt": '"Onlar öğrenciler." cümlesi için doğru fiil hangisidir?',
        "options": ["sind", "ist", "seid"],
        "correct": "sind",
        "explanation": "Onlar anlamındaki sie çoğuldur; sind ile kullanılır.",
    },
    {
        "id": "a1-161",
        "module_id": "identity",
        "prompt": '"on dört" sayısının doğru Almancası hangisidir?',
        "options": ["vierzehn", "vierzig", "fünfzehn"],
        "correct": "vierzehn",
        "explanation": "14 sayısı vierzehn olarak yazılır.",
    },
    {
        "id": "a1-162",
        "module_id": "identity",
        "prompt": '"Sen 25 yaşındasın." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Du bist 25 Jahre alt.", "Du hast 25 Jahre.", "Du bist alt 25 Jahre."],
        "correct": "Du bist 25 Jahre alt.",
        "explanation": "Yaş cümlesi du zamiriyle de sein fiili üzerinden kurulur.",
    },
    {
        "id": "a1-163",
        "module_id": "identity",
        "prompt": '"Biz Berlin\'deyiz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir sind in Berlin.", "Wir sind aus Berlin.", "Wir kommen in Berlin."],
        "correct": "Wir sind in Berlin.",
        "explanation": "Bulunulan yer bilgisi in ile verilir.",
    },
    {
        "id": "a1-164",
        "module_id": "identity",
        "prompt": '"O Fransa\'dan geliyor." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Er kommt aus Frankreich.", "Er kommt in Frankreich.", "Er ist Frankreich."],
        "correct": "Er kommt aus Frankreich.",
        "explanation": "Köken ve geldiği yer bilgisinde aus kullanılır.",
    },
    {
        "id": "a1-165",
        "module_id": "identity",
        "prompt": '"Biz Avusturyalıyız." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir sind österreichisch.", "Wir sind Österreich.", "Wir heißen österreichisch."],
        "correct": "Wir sind österreichisch.",
        "explanation": "Milliyet/dil bilgisi çoğu zaman sıfat biçimiyle kurulur.",
    },
    {
        "id": "a1-166",
        "module_id": "identity",
        "prompt": 'Doğru soru hangisidir?',
        "options": ["Woher kommst du?", "Woher du kommst?", "Du woher kommst?"],
        "correct": "Woher kommst du?",
        "explanation": "Soru kelimesinden sonra çekimli fiil gelir.",
    },
    {
        "id": "a1-167",
        "module_id": "identity",
        "prompt": '"Ne öğreniyorsun?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Was lernst du?", "Wer lernst du?", "Wann lernst du?"],
        "correct": "Was lernst du?",
        "explanation": "İçerik/nesne sormak için was kullanılır.",
    },
    {
        "id": "a1-168",
        "module_id": "identity",
        "prompt": '"Sen kimsin?" sorusuna uygun cevap hangisidir?',
        "options": ["Ich bin Eren.", "Ich bin aus Eren.", "Ich habe Eren."],
        "correct": "Ich bin Eren.",
        "explanation": "Kimlik sorusuna sein ile kısa cevap verilebilir.",
    },
    {
        "id": "a1-169",
        "module_id": "identity",
        "prompt": '"Nerede yaşıyorsunuz?" sorusunun resmî doğru karşılığı hangisidir?',
        "options": ["Wo wohnen Sie?", "Wo wohnen ihr?", "Woher wohnen Sie?"],
        "correct": "Wo wohnen Sie?",
        "explanation": "Resmî hitapta Sie zamiri ve uygun çekim kullanılır.",
    },
    {
        "id": "a1-170",
        "module_id": "identity",
        "prompt": '"Onlar Almanya\'dan geliyor." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Sie kommen aus Deutschland.", "Sie kommen in Deutschland.", "Sie sind aus Deutschland."],
        "correct": "Sie kommen aus Deutschland.",
        "explanation": "Gelinen yer / köken için kommen aus kalıbı doğal kullanımdır.",
    },
    {
        "id": "a1-171",
        "module_id": "daily_life",
        "prompt": '"Benim bir bilgisayarım var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich habe einen Computer.", "Ich habe ein Computer.", "Ich bin einen Computer."],
        "correct": "Ich habe einen Computer.",
        "explanation": "Computer maskulin isimdir; sahiplikte einen Computer kullanılır.",
    },
    {
        "id": "a1-172",
        "module_id": "daily_life",
        "prompt": '"onun çantası" ifadesinin doğru biçimi hangisidir?',
        "options": ["seine Tasche", "sein Tasche", "sie Tasche"],
        "correct": "seine Tasche",
        "explanation": "Tasche dişildir; burada doğru biçim seine Tasche olur.",
    },
    {
        "id": "a1-173",
        "module_id": "daily_life",
        "prompt": '"Bu bizim kitabımız." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist unser Buch.", "Das ist unsere Buch.", "Wir haben unser Buch ist."],
        "correct": "Das ist unser Buch.",
        "explanation": "Buch nötr olduğu için unser Buch biçimi kullanılır.",
    },
    {
        "id": "a1-174",
        "module_id": "daily_life",
        "prompt": '"Her sabah kahve içiyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich trinke jeden Morgen Kaffee.", "Ich jeden Morgen trinke Kaffee.", "Jeden Morgen ich trinke Kaffee."],
        "correct": "Ich trinke jeden Morgen Kaffee.",
        "explanation": "Düz cümlede özne + fiil + zaman + nesne sıralaması korunur.",
    },
    {
        "id": "a1-175",
        "module_id": "daily_life",
        "prompt": '"Pazartesi günü saat sekizde çalışıyoruz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir arbeiten am Montag um acht Uhr.", "Wir arbeiten um Montag am acht Uhr.", "Am Montag wir arbeiten um acht Uhr."],
        "correct": "Wir arbeiten am Montag um acht Uhr.",
        "explanation": "Gün için am, saat için um kullanılır.",
    },
    {
        "id": "a1-176",
        "module_id": "daily_life",
        "prompt": 'Zaman başta olan doğru cümle hangisidir?',
        "options": ["Heute arbeiten wir nicht.", "Heute wir arbeiten nicht.", "Wir heute arbeiten nicht."],
        "correct": "Heute arbeiten wir nicht.",
        "explanation": "Zaman ifadesi başta olduğunda fiil ikinci pozisyonda kalır.",
    },
    {
        "id": "a1-177",
        "module_id": "daily_life",
        "prompt": '"Bizim bir okulumuz yok." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir haben keine Schule.", "Wir haben kein Schule.", "Wir sind keine Schule."],
        "correct": "Wir haben keine Schule.",
        "explanation": "Schule dişildir; isim olumsuzluğu keine Schule ile kurulur.",
    },
    {
        "id": "a1-178",
        "module_id": "daily_life",
        "prompt": '"Akşamları evde kitap okuyor." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Abends liest er zu Hause ein Buch.", "Abends er liest zu Hause ein Buch.", "Er abends liest zu Hause ein Buch."],
        "correct": "Abends liest er zu Hause ein Buch.",
        "explanation": "Başta zaman varsa fiil ikinci sırada yer alır.",
    },
    {
        "id": "a1-179",
        "module_id": "daily_life",
        "prompt": '"Ne zaman işe gidiyorsun?" sorusunun doğru Almancası hangisidir?',
        "options": ["Wann gehst du zur Arbeit?", "Wo gehst du zur Arbeit?", "Wer gehst du zur Arbeit?"],
        "correct": "Wann gehst du zur Arbeit?",
        "explanation": "Zaman sormak için wann kullanılır.",
    },
    {
        "id": "a1-180",
        "module_id": "daily_life",
        "prompt": '"Benim bir erkek kardeşim var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich habe einen Bruder.", "Ich habe ein Bruder.", "Ich bin einen Bruder."],
        "correct": "Ich habe einen Bruder.",
        "explanation": "Bruder maskulin isimdir; haben ile einen Bruder gerekir.",
    },
    {
        "id": "a1-181",
        "module_id": "space_time",
        "prompt": '"Bu bir banyo." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist ein Bad.", "Das ist eine Bad.", "Es gibt der Bad."],
        "correct": "Das ist ein Bad.",
        "explanation": "Bad nötr isimdir; yeni tanıtımda ein Bad kullanılır.",
    },
    {
        "id": "a1-182",
        "module_id": "space_time",
        "prompt": '"Burada bir masa var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Es gibt hier einen Tisch.", "Es gibt hier ein Tisch.", "Hier gibt einen Tisch es."],
        "correct": "Es gibt hier einen Tisch.",
        "explanation": "Tisch maskulin isimdir; Es gibt yapısında einen Tisch kullanılır.",
    },
    {
        "id": "a1-183",
        "module_id": "space_time",
        "prompt": '"Anahtar nerede?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Wo ist der Schlüssel?", "Woher ist der Schlüssel?", "Wann ist der Schlüssel?"],
        "correct": "Wo ist der Schlüssel?",
        "explanation": "Yer sormak için Wo ist ...? kalıbı kullanılır.",
    },
    {
        "id": "a1-184",
        "module_id": "space_time",
        "prompt": '"Saat üç." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Es ist drei Uhr.", "Es drei Uhr.", "Es ist um drei."],
        "correct": "Es ist drei Uhr.",
        "explanation": "Tam saat söylemenin temel kalıbı Es ist ... Uhr biçimidir.",
    },
    {
        "id": "a1-185",
        "module_id": "space_time",
        "prompt": '"Saat dört buçuk." ifadesinin doğru Almancası hangisidir?',
        "options": ["Es ist halb fünf.", "Es ist halb vier.", "Es ist Viertel nach vier."],
        "correct": "Es ist halb fünf.",
        "explanation": "Almanca yarım saat bir sonraki saate göre kurulur.",
    },
    {
        "id": "a1-186",
        "module_id": "space_time",
        "prompt": '"Cumartesi günü evdeyiz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir sind am Samstag zu Hause.", "Wir sind um Samstag zu Hause.", "Am Samstag wir sind zu Hause."],
        "correct": "Wir sind am Samstag zu Hause.",
        "explanation": "Gün adıyla temel yapı am + gün şeklindedir.",
    },
    {
        "id": "a1-187",
        "module_id": "space_time",
        "prompt": '"Saat 8\'den 10\'a kadar dersim var." cümlesine en yakın doğru seçenek hangisidir?',
        "options": ["Ich habe Unterricht von acht bis zehn.", "Ich habe Unterricht um acht bis zehn.", "Ich habe von acht um zehn Unterricht."],
        "correct": "Ich habe Unterricht von acht bis zehn.",
        "explanation": "Zaman aralığı vermek için von ... bis ... kullanılır.",
    },
    {
        "id": "a1-188",
        "module_id": "space_time",
        "prompt": '"Ben saat altıda eve dönüyorum." cümlesinin ayrılabilen fiilli doğru karşılığı hangisidir?',
        "options": ["Ich komme um sechs Uhr nach Hause zurück.", "Ich zurückkomme um sechs Uhr nach Hause.", "Ich komme zurück um sechs Uhr nach Hause zurück."],
        "correct": "Ich komme um sechs Uhr nach Hause zurück.",
        "explanation": "Ayrılabilen fiilde çekimli kısım önde, ayrılan parça sonda kalır.",
    },
    {
        "id": "a1-189",
        "module_id": "space_time",
        "prompt": '"Mutfak orada." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Die Küche ist dort.", "Die Küche dort ist.", "Dort die Küche ist."],
        "correct": "Die Küche ist dort.",
        "explanation": "Kısa yer bildiriminde yüklem cümlesi normal sırayla kurulabilir.",
    },
    {
        "id": "a1-190",
        "module_id": "space_time",
        "prompt": '"Ben ne zaman arıyorum?" anlamına en yakın soru hangisidir?',
        "options": ["Wann rufe ich an?", "Wann ich rufe an?", "Wo rufe ich an?"],
        "correct": "Wann rufe ich an?",
        "explanation": "Soru kelimesi + çekimli fiil + özne sırası korunur; ayrılan parça sonda kalır.",
    },
    {
        "id": "a1-191",
        "module_id": "objects_orders",
        "prompt": '"Bir kahve istiyor musunuz?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Möchten Sie einen Kaffee?", "Möchten Sie ein Kaffee?", "Sie möchten einen Kaffee?"],
        "correct": "Möchten Sie einen Kaffee?",
        "explanation": "Kibar teklif ya da istek sorusunda maskulin nesne için einen kullanılır.",
    },
    {
        "id": "a1-192",
        "module_id": "objects_orders",
        "prompt": '"Ben bir pizza ve bir salata sipariş ediyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bestelle eine Pizza und einen Salat.", "Ich bestelle eine Pizza und ein Salat.", "Ich bin eine Pizza und einen Salat."],
        "correct": "Ich bestelle eine Pizza und einen Salat.",
        "explanation": "Pizza dişil, Salat maskulin nesnedir; ikisi farklı biçimde çekilir.",
    },
    {
        "id": "a1-193",
        "module_id": "objects_orders",
        "prompt": '"Garsonu arıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich suche den Kellner.", "Ich suche der Kellner.", "Ich suche dem Kellner."],
        "correct": "Ich suche den Kellner.",
        "explanation": "Kellner maskulin nesnedir; suchen ile den Kellner kullanılır.",
    },
    {
        "id": "a1-194",
        "module_id": "objects_orders",
        "prompt": '"Ben portakal suyunu almıyorum." cümlesine en yakın doğru seçenek hangisidir?',
        "options": ["Ich nehme keinen Saft.", "Ich nehme keine Saft.", "Ich nehme nicht Saft."],
        "correct": "Ich nehme keinen Saft.",
        "explanation": "Saft maskulin isimdir; olumsuz biçimi keinen Saft olur.",
    },
    {
        "id": "a1-195",
        "module_id": "objects_orders",
        "prompt": '"Müşteri ne alıyor?" sorusunun doğru Almancası hangisidir?',
        "options": ["Was nimmt der Gast?", "Wen nimmt der Gast?", "Wo nimmt der Gast?"],
        "correct": "Was nimmt der Gast?",
        "explanation": "Cansız nesne/içerik sorulduğu için was kullanılır.",
    },
    {
        "id": "a1-196",
        "module_id": "objects_orders",
        "prompt": '"Ben menüyü görüyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich sehe die Speisekarte.", "Ich sehe den Speisekarte.", "Ich sehe das Speisekarte."],
        "correct": "Ich sehe die Speisekarte.",
        "explanation": "Speisekarte dişil nesnedir; die biçimi korunur.",
    },
    {
        "id": "a1-197",
        "module_id": "objects_orders",
        "prompt": '"Bir kahve ne kadar?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Was kostet ein Kaffee?", "Wie kostet ein Kaffee?", "Wo kostet ein Kaffee?"],
        "correct": "Was kostet ein Kaffee?",
        "explanation": "Fiyat sormak için Was kostet ...? kullanılır.",
    },
    {
        "id": "a1-198",
        "module_id": "objects_orders",
        "prompt": '"Ben ekmeği satın alıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich kaufe das Brot.", "Ich kaufe den Brot.", "Ich kaufe dem Brot."],
        "correct": "Ich kaufe das Brot.",
        "explanation": "Brot nötr nesnedir; Akkusativde biçim değişmez.",
    },
    {
        "id": "a1-199",
        "module_id": "objects_orders",
        "prompt": '"Bir çorba daha ister misiniz?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Möchten Sie noch eine Suppe?", "Möchten Sie noch einen Suppe?", "Sie möchten noch eine Suppe?"],
        "correct": "Möchten Sie noch eine Suppe?",
        "explanation": "Suppe dişildir; teklif sorusunda eine Suppe kullanılır.",
    },
    {
        "id": "a1-200",
        "module_id": "objects_orders",
        "prompt": '"Garson hesap getiriyor." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Der Kellner bringt die Rechnung.", "Der Kellner bringt den Rechnung.", "Der Kellner bringt das Rechnung."],
        "correct": "Der Kellner bringt die Rechnung.",
        "explanation": "Rechnung dişil nesnedir; die Rechnung biçimi kullanılır.",
    },
    {
        "id": "a1-201",
        "module_id": "foundations",
        "prompt": 'Akşam saatlerinde uygun selamlaşma kalıbı hangisidir?',
        "options": ["Guten Abend!", "Guten Morgen!", "Auf Wiedersehen!"],
        "correct": "Guten Abend!",
        "explanation": "Akşam karşılaşmalarında en temel kalıp Guten Abend olur.",
    },
    {
        "id": "a1-202",
        "module_id": "foundations",
        "prompt": '"___ Frau Schneider" boşluğuna hangi artikel gelir?',
        "options": ["der", "die", "das"],
        "correct": "die",
        "explanation": "Frau dişil isimdir; die Frau kullanılır.",
    },
    {
        "id": "a1-203",
        "module_id": "foundations",
        "prompt": 'Kısa bir vedalaşmada en doğal seçenek hangisidir?',
        "options": ["Tschüss!", "Guten Tag!", "Wer bist du?"],
        "correct": "Tschüss!",
        "explanation": "Gündelik vedalaşmada en temel kalıp Tschüss olur.",
    },
    {
        "id": "a1-204",
        "module_id": "foundations",
        "prompt": '"Ben yorgunum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bin müde.", "Ich bist müde.", "Ich habe müde."],
        "correct": "Ich bin müde.",
        "explanation": "Durum bildiren bu tür cümleler sein ile kurulur: Ich bin müde.",
    },
    {
        "id": "a1-205",
        "module_id": "foundations",
        "prompt": 'wir zamiri ile sein fiilinin doğru çekimi hangisidir?',
        "options": ["seid", "sind", "bin"],
        "correct": "sind",
        "explanation": "wir ile sein fiili sind olarak çekilir.",
    },
    {
        "id": "a1-206",
        "module_id": "foundations",
        "prompt": '"ihr" zamirinin en yakın Türkçe karşılığı hangisidir?',
        "options": ["siz", "biz", "onlar"],
        "correct": "siz",
        "explanation": "ihr, gündelik çoğul ikinci kişi yani siz anlamındadır.",
    },
    {
        "id": "a1-207",
        "module_id": "foundations",
        "prompt": '"Guten Tag, Herr Aydın." ifadesi ne yapar?',
        "options": ["Birini kibar biçimde selamlar.", "Birine veda eder.", "Birinin yaşını sorar."],
        "correct": "Birini kibar biçimde selamlar.",
        "explanation": "Guten Tag resmi veya nötr selamlaşma kalıbıdır.",
    },
    {
        "id": "a1-208",
        "module_id": "foundations",
        "prompt": '"Wie geht es dir?" sorusuna kısa ve doğal cevap hangisidir?',
        "options": ["Mir geht es so lala.", "Ich heiße gut.", "Ich bin dir gut."],
        "correct": "Mir geht es so lala.",
        "explanation": "Hâl-hatır sorusuna Mir geht es ... kalıbıyla cevap verilir.",
    },
    {
        "id": "a1-209",
        "module_id": "foundations",
        "prompt": '"Bu bir masa." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist ein Tisch.", "Das ist der Tisch.", "Ein Tisch das ist."],
        "correct": "Das ist ein Tisch.",
        "explanation": "Bir nesneyi ilk kez tanıtırken Das ist ein ... kalıbı doğal olur.",
    },
    {
        "id": "a1-210",
        "module_id": "foundations",
        "prompt": 'Lampe kelimesinin doğru artikeli hangisidir?',
        "options": ["der", "die", "das"],
        "correct": "die",
        "explanation": "Lamba Almancada die Lampe olarak kullanılır.",
    },
    {
        "id": "a1-211",
        "module_id": "identity",
        "prompt": '"Woher kommt ihr?" sorusunun Türkçesi hangisidir?',
        "options": ["Siz nereden geliyorsunuz?", "Siz nerede yaşıyorsunuz?", "Siz ne öğreniyorsunuz?"],
        "correct": "Siz nereden geliyorsunuz?",
        "explanation": "Woher, köken veya geldiğin yer bilgisini sorar.",
    },
    {
        "id": "a1-212",
        "module_id": "identity",
        "prompt": '"Sie kommt aus Spanien." cümlesinin doğru Türkçesi hangisidir?',
        "options": ["O İspanya'dan geliyor.", "O İspanya'da yaşıyor.", "O İspanyolca öğreniyor."],
        "correct": "O İspanya'dan geliyor.",
        "explanation": "aus Spanien, İspanya'dan anlamı verir; bu köken bilgisidir.",
    },
    {
        "id": "a1-213",
        "module_id": "identity",
        "prompt": '"Ben otuz yaşındayım." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bin dreißig Jahre alt.", "Ich habe dreißig Jahre.", "Ich heiße dreißig Jahre alt."],
        "correct": "Ich bin dreißig Jahre alt.",
        "explanation": "Yaş, Almancada sein ile kurulur; haben kullanılmaz.",
    },
    {
        "id": "a1-214",
        "module_id": "identity",
        "prompt": '"Ich komme aus Wien." cevabına en uygun soru hangisidir?',
        "options": ["Woher kommst du?", "Wie heißt du?", "Wo wohnst du?"],
        "correct": "Woher kommst du?",
        "explanation": "aus + şehir/ülke cevabı, köken sorusu olan Woher kommst du? ile eşleşir.",
    },
    {
        "id": "a1-215",
        "module_id": "identity",
        "prompt": '"Wo wohnst du?" sorusuna uygun cevap hangisidir?',
        "options": ["Ich wohne in Köln.", "Ich komme aus Köln.", "Ich bin Köln."],
        "correct": "Ich wohne in Köln.",
        "explanation": "Yaşanılan yer için wohnen + in kullanılır.",
    },
    {
        "id": "a1-216",
        "module_id": "identity",
        "prompt": '"Bugün nerede çalışıyorsun?" sorusunun doğru dizilişi hangisidir?',
        "options": ["Wo arbeitest du heute?", "Wo du arbeitest heute?", "Du wo arbeitest heute?"],
        "correct": "Wo arbeitest du heute?",
        "explanation": "Soru kelimesinden sonra çekimli fiil gelir; burada fiil arbeitest olur.",
    },
    {
        "id": "a1-217",
        "module_id": "identity",
        "prompt": '"Onun adı Lara." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Sie heißt Lara.", "Sie ist Lara heißt.", "Ihr Name Lara bin."],
        "correct": "Sie heißt Lara.",
        "explanation": "Ad söyleme kalıbı üçüncü tekilde heißt ile kurulur.",
    },
    {
        "id": "a1-218",
        "module_id": "identity",
        "prompt": "\"Biz Berlin'de çalışıyoruz.\" cümlesinin doğru karşılığı hangisidir?",
        "options": ["Wir arbeiten in Berlin.", "Wir arbeiten aus Berlin.", "Wir sind arbeiten Berlin."],
        "correct": "Wir arbeiten in Berlin.",
        "explanation": "Bulunulan/çalışılan yer için in + şehir kullanılır.",
    },
    {
        "id": "a1-219",
        "module_id": "identity",
        "prompt": "\"Sen Almanya'dan mısın?\" sorusunun doğru Almancası hangisidir?",
        "options": ["Kommst du aus Deutschland?", "Kommst du in Deutschland?", "Du kommst aus Deutschland?"],
        "correct": "Kommst du aus Deutschland?",
        "explanation": "Evet-hayır sorusunda fiil başa geçer; köken için aus kullanılır.",
    },
    {
        "id": "a1-220",
        "module_id": "identity",
        "prompt": '"Wer ist das?" sorusu ne sorar?',
        "options": ["Bu kim?", "Bu nerede?", "Bu kaç yaşında?"],
        "correct": "Bu kim?",
        "explanation": "wer kişi sorar; tanıtma bağlamında Bu kim? anlamına gelir.",
    },
    {
        "id": "a1-221",
        "module_id": "daily_life",
        "prompt": '"Benim bir odam var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich habe ein Zimmer.", "Ich bin ein Zimmer.", "Ich habe der Zimmer."],
        "correct": "Ich habe ein Zimmer.",
        "explanation": "Sahiplik haben ile kurulur; Zimmer nötr isimdir.",
    },
    {
        "id": "a1-222",
        "module_id": "daily_life",
        "prompt": '"Bu benim babam." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Das ist mein Vater.", "Ich habe mein Vater.", "Mein Vater ist das ich."],
        "correct": "Das ist mein Vater.",
        "explanation": "Birini tanıtırken Das ist ... kalıbı kullanılır.",
    },
    {
        "id": "a1-223",
        "module_id": "daily_life",
        "prompt": '"Onun bir evi var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Er hat ein Haus.", "Er ist ein Haus.", "Er hat einen Haus."],
        "correct": "Er hat ein Haus.",
        "explanation": "Haus nötr isimdir; ein Haus kullanılır.",
    },
    {
        "id": "a1-224",
        "module_id": "daily_life",
        "prompt": '"Sabahları Almanca çalışıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Morgens lerne ich Deutsch.", "Am morgens lerne ich Deutsch.", "Morgens ich lerne Deutsch."],
        "correct": "Morgens lerne ich Deutsch.",
        "explanation": "morgens yalın zaman zarfıdır; başa geldiğinde fiil ikinci sırada kalır.",
    },
    {
        "id": "a1-225",
        "module_id": "daily_life",
        "prompt": '"Akşamları çay içiyoruz." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Abends trinken wir Tee.", "Am abends trinken wir Tee.", "Wir abends Tee trinken."],
        "correct": "Abends trinken wir Tee.",
        "explanation": "abends de zaman zarfıdır; fiil yine ikinci pozisyondadır.",
    },
    {
        "id": "a1-226",
        "module_id": "daily_life",
        "prompt": '"Bugün çok çalışıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Heute arbeite ich viel.", "Heute ich arbeite viel.", "Ich heute viel arbeite."],
        "correct": "Heute arbeite ich viel.",
        "explanation": "Bugün anlamı veren Heute cümle başına gelebilir; fiil ikinci sırada kalır.",
    },
    {
        "id": "a1-227",
        "module_id": "daily_life",
        "prompt": '"Pazar günü evdeyim." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Am Sonntag bin ich zu Hause.", "Um Sonntag bin ich zu Hause.", "Am Sonntag ich bin zu Hause."],
        "correct": "Am Sonntag bin ich zu Hause.",
        "explanation": "Gün adları ile am kullanılır; fiil ikinci sıradadır.",
    },
    {
        "id": "a1-228",
        "module_id": "daily_life",
        "prompt": '"Bizim iki çocuğumuz var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Wir haben zwei Kinder.", "Wir sind zwei Kinder.", "Wir haben zwei Kind."],
        "correct": "Wir haben zwei Kinder.",
        "explanation": "Kind kelimesinin çoğulu Kinder olur ve sahiplik haben ile kurulur.",
    },
    {
        "id": "a1-229",
        "module_id": "daily_life",
        "prompt": '"Senin telefonun var mı?" sorusunun doğru Almancası hangisidir?',
        "options": ["Hast du ein Handy?", "Bist du ein Handy?", "Hast du der Handy?"],
        "correct": "Hast du ein Handy?",
        "explanation": "haben ile soru yapılırken fiil başa geçer; Handy nötrdür.",
    },
    {
        "id": "a1-230",
        "module_id": "daily_life",
        "prompt": '"Öğleden sonra bir kitap okuyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Am Nachmittag lese ich ein Buch.", "Am Nachmittag ich lese ein Buch.", "Nachmittag lese ich am ein Buch."],
        "correct": "Am Nachmittag lese ich ein Buch.",
        "explanation": "Belirli zaman bloğu için am Nachmittag kullanılır; fiil ikinci sıradadır.",
    },
    {
        "id": "a1-231",
        "module_id": "space_time",
        "prompt": '"Mutfakta bir masa var." cümlesinin doğru karşılığı hangisidir?',
        "options": ["In der Küche gibt es einen Tisch.", "In der Küche gibt einen Tisch es.", "In die Küche gibt es ein Tisch."],
        "correct": "In der Küche gibt es einen Tisch.",
        "explanation": "Es gibt yapısı nesne alır; Tisch maskulin olduğu için einen Tisch olur.",
    },
    {
        "id": "a1-232",
        "module_id": "space_time",
        "prompt": '"Burada bir sandalye yok." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Hier gibt es keinen Stuhl.", "Hier gibt es kein Stuhl.", "Hier ist keinen Stuhl."],
        "correct": "Hier gibt es keinen Stuhl.",
        "explanation": "Maskulin isimlerde olumsuz Akkusativ biçimi keinen olur.",
    },
    {
        "id": "a1-233",
        "module_id": "space_time",
        "prompt": '"Anahtar nerede?" sorusunun doğru Almancası hangisidir?',
        "options": ["Wo ist der Schlüssel?", "Woher ist der Schlüssel?", "Wann ist der Schlüssel?"],
        "correct": "Wo ist der Schlüssel?",
        "explanation": "Yer sormak için Wo ist ...? kullanılır.",
    },
    {
        "id": "a1-234",
        "module_id": "space_time",
        "prompt": '"Saat üç buçuk." ifadesinin doğru karşılığı hangisidir?',
        "options": ["Es ist halb vier.", "Es ist drei halb.", "Es ist Viertel vor drei."],
        "correct": "Es ist halb vier.",
        "explanation": "Almancada halb vier, üç buçuk anlamına gelir.",
    },
    {
        "id": "a1-235",
        "module_id": "space_time",
        "prompt": '"Saat dördü çeyrek geçiyor." ifadesinin doğru karşılığı hangisidir?',
        "options": ["Es ist Viertel nach vier.", "Es ist Viertel vor vier.", "Es ist halb fünf."],
        "correct": "Es ist Viertel nach vier.",
        "explanation": "Viertel nach dört çeyrek geçe anlamındadır.",
    },
    {
        "id": "a1-236",
        "module_id": "space_time",
        "prompt": '"Saat beşe çeyrek var." ifadesinin doğru karşılığı hangisidir?',
        "options": ["Es ist Viertel vor fünf.", "Es ist Viertel nach fünf.", "Es ist halb fünf."],
        "correct": "Es ist Viertel vor fünf.",
        "explanation": "Viertel vor beşe çeyrek var anlamına gelir.",
    },
    {
        "id": "a1-237",
        "module_id": "space_time",
        "prompt": '"Ders pazartesiden cumaya." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Der Kurs ist von Montag bis Freitag.", "Der Kurs ist am Montag bis Freitag.", "Der Kurs von Montag am Freitag ist."],
        "correct": "Der Kurs ist von Montag bis Freitag.",
        "explanation": "von ... bis ... aralık bildirir; günler bu yapıyla doğal kullanılır.",
    },
    {
        "id": "a1-238",
        "module_id": "space_time",
        "prompt": '"Ben saat sekizde kalkıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich stehe um acht Uhr auf.", "Ich aufstehe um acht Uhr.", "Ich stehe auf um acht Uhr."],
        "correct": "Ich stehe um acht Uhr auf.",
        "explanation": "Ayrılabilen fiilde çekimli parça ikinci sıraya, ayrılan parça sona gider.",
    },
    {
        "id": "a1-239",
        "module_id": "space_time",
        "prompt": '"O şimdi alışveriş yapıyor." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Er kauft jetzt ein.", "Er einkauft jetzt.", "Er jetzt kauft ein."],
        "correct": "Er kauft jetzt ein.",
        "explanation": "einkaufen ayrılabilen fiildir; kauft ikinci sırada, ein sonda gelir.",
    },
    {
        "id": "a1-240",
        "module_id": "space_time",
        "prompt": '"Burada bir süpermarket var mı?" sorusunun doğru Almancası hangisidir?',
        "options": ["Gibt es hier einen Supermarkt?", "Hier gibt es einen Supermarkt?", "Ist hier einen Supermarkt?"],
        "correct": "Gibt es hier einen Supermarkt?",
        "explanation": "Var mı? sorusu Gibt es ...? ile kurulur.",
    },
    {
        "id": "a1-241",
        "module_id": "objects_orders",
        "prompt": '"Ben çayı alıyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich nehme den Tee.", "Ich nehme der Tee.", "Ich nehme dem Tee."],
        "correct": "Ich nehme den Tee.",
        "explanation": "Tee maskulin nesnedir; Akkusativde den Tee olur.",
    },
    {
        "id": "a1-242",
        "module_id": "objects_orders",
        "prompt": '"Bir su alayım." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich nehme ein Wasser.", "Ich nehme einen Wasser.", "Ich möchte der Wasser."],
        "correct": "Ich nehme ein Wasser.",
        "explanation": "Wasser nötr isimdir; siparişte bir su için ein Wasser denir.",
    },
    {
        "id": "a1-243",
        "module_id": "objects_orders",
        "prompt": '"Menüyü getirir misiniz, lütfen?" cümlesinin doğru karşılığı hangisidir?',
        "options": ["Bringen Sie bitte die Speisekarte?", "Bitte bringen Sie die Speisekarte.", "Sie bringen bitte die Speisekarte."],
        "correct": "Bitte bringen Sie die Speisekarte.",
        "explanation": "Kibar istek için Bitte bringen Sie ... kalıbı doğal ve doğru olur.",
    },
    {
        "id": "a1-244",
        "module_id": "objects_orders",
        "prompt": '"Hesap lütfen." ifadesinin doğru karşılığı hangisidir?',
        "options": ["Die Rechnung, bitte.", "Die Speisekarte, bitte.", "Ich nehme Rechnung."],
        "correct": "Die Rechnung, bitte.",
        "explanation": "Restoranda hesap istemenin en temel kısa kalıbı budur.",
    },
    {
        "id": "a1-245",
        "module_id": "objects_orders",
        "prompt": '"Ben elma suyu istemiyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich nehme keinen Apfelsaft.", "Ich nehme kein Apfelsaft.", "Ich nehme nicht Apfelsaft."],
        "correct": "Ich nehme keinen Apfelsaft.",
        "explanation": "Apfelsaft maskulin isimdir; olumsuz Akkusativ biçimi keinen olur.",
    },
    {
        "id": "a1-246",
        "module_id": "objects_orders",
        "prompt": '"Bir pizza ve bir salata istiyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich möchte eine Pizza und einen Salat.", "Ich möchte einen Pizza und eine Salat.", "Ich möchte Pizza und Salat einen."],
        "correct": "Ich möchte eine Pizza und einen Salat.",
        "explanation": "Pizza dişildir; Salat maskulindir ve Akkusativde einen olur.",
    },
    {
        "id": "a1-247",
        "module_id": "objects_orders",
        "prompt": '"Garson çorbayı getiriyor." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Der Kellner bringt die Suppe.", "Der Kellner bringt den Suppe.", "Der Kellner bringt das Suppe."],
        "correct": "Der Kellner bringt die Suppe.",
        "explanation": "Suppe dişil nesnedir; die Suppe biçimi korunur.",
    },
    {
        "id": "a1-248",
        "module_id": "objects_orders",
        "prompt": '"Çay ne kadar?" sorusunun doğru karşılığı hangisidir?',
        "options": ["Was kostet der Tee?", "Wie kostet der Tee?", "Wo kostet der Tee?"],
        "correct": "Was kostet der Tee?",
        "explanation": "Fiyat sorusu Was kostet ...? ile kurulur.",
    },
    {
        "id": "a1-249",
        "module_id": "objects_orders",
        "prompt": '"Ben sandviçi sipariş ediyorum." cümlesinin doğru karşılığı hangisidir?',
        "options": ["Ich bestelle das Sandwich.", "Ich bestelle den Sandwich.", "Ich bestelle dem Sandwich."],
        "correct": "Ich bestelle das Sandwich.",
        "explanation": "Sandwich burada nötr nesne olarak kullanılır; das Sandwich denir.",
    },
    {
        "id": "a1-250",
        "module_id": "objects_orders",
        "prompt": '"Ben kahveyi değil çayı alıyorum." cümlesine en yakın doğru seçenek hangisidir?',
        "options": ["Ich nehme nicht den Kaffee, sondern den Tee.", "Ich nehme den Kaffee nicht sondern Tee.", "Ich nehme keinen Kaffee und den Tee."],
        "correct": "Ich nehme nicht den Kaffee, sondern den Tee.",
        "explanation": "İki seçenek arasında düzeltme yapılırken nicht ..., sondern ... hattı kullanılır.",
    },
]


LEVEL_TEST_BANKS = {
    "a1": A1_LEVEL_TEST_BANK,
}


def _build_assessment_question(question, rng):
    prepared = deepcopy(question)
    options = list(prepared["options"])
    correct = prepared["correct"]
    rng.shuffle(options)
    prepared["options"] = options
    prepared["correct_index"] = options.index(correct)
    return prepared


def get_level_test_bank_size(level_slug):
    return len(LEVEL_TEST_BANKS.get(level_slug, []))


def build_german_level_test(level_slug):
    if level_slug != "a1":
        return None

    rng = SystemRandom()
    bank = LEVEL_TEST_BANKS.get(level_slug, [])
    if not bank:
        return None

    exercises = []
    total_questions = 0

    for module in A1_LEVEL_TEST_MODULES:
        pool = [item for item in bank if item["module_id"] == module["id"]]
        sample_size = min(module["sample_size"], len(pool))
        selected = rng.sample(pool, sample_size)
        questions = [_build_assessment_question(item, rng) for item in selected]
        rng.shuffle(questions)
        total_questions += len(questions)
        exercises.append(
            {
                "id": f'level-test-{module["id"]}',
                "type": "single_choice",
                "title": module["title"],
                "description": module["description"],
                "questions": questions,
            }
        )

    return {
        "slug": f"{level_slug}-seviye-bitirme-testi",
        "title": "A1 Seviye Bitirme Testi",
        "subtitle": "Dersleri bitirdikten sonra temeli gerçekten oturtup oturtmadığını ölç.",
        "duration": "35-45 dk",
        "question_bank_size": len(bank),
        "sample_size": total_questions,
        "pass_score": 80,
        "pass_correct": 40,
        "module_count": len(exercises),
        "instructions": [
            "Test her açıldığında soru bankasından yeni bir karışım seçilir.",
            "Her modülde farklı derslerden gelen çekirdek yapılar ölçülür.",
            "Bu oturum 50 sorudan oluşur; 40 doğru ve üzeri sonuç geçer kabul edilir.",
            "Yüzde 80 ve üzeri, A1 temel omurgasının oturduğunu gösterir; düşük kalırsa özellikle zayıf modülleri tekrar etmen gerekir.",
            "Bu bankaya her geliştirme turunda 50 yeni soru eklenebilir; yapı buna göre kuruldu.",
        ],
        "focus_points": [
            "Artikel ve temel tanışma kalıpları",
            "sein / haben / düzenli fiiller",
            "zaman ve program cümleleri",
            "mekân soruları ve Es gibt",
            "Akkusativ ve sipariş kalıpları",
        ],
        "exercises": exercises,
    }
